### ISSUE TITLE
Clear up license

### ISSUE THREAD

**Issue by mibalan** [faisalman/ua-parser-js#1]
It's very unclear to me whether the code is licensed only under GPLv2+ or it's dual-licensed under GPLv2+ _and_ MIT.
The Readme first states it's GPL+MIT, but then, under the License heading it only mentions GPL (as does the code).

So, which one is it?

It's a pretty important issue for me because it will determine if I can use it in a project or not :)

Thanks in advance!

**Comment by LManiu** [comment]
Hi,

Let me first say to you - great work! I am wondering if I can use the UA-Parser in a commercial product with a proprietary license. I see the UA-Parser is "Dual licensed under GPLv2 & MIT". Does this mean the UA-Parser may be distributed under either license (MIT in my case)?

Thanks in advance

**Comment by faisalman** [comment]
Hi LManiu, thanks, sure you can choose whether to use it under GPL or MIT.
Good luck with your project ;)
