### ISSUE TITLE
IE8 is not correctly determined when in compatibility view

### ISSUE THREAD

**Issue by hhumml** [faisalman/ua-parser-js#103]
Even if IE8 is forced to edge mode using

```
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
```

its version indicates IE7. The ua-parser.js should also consider the document.documentMode in this case which tells that the browser is IE8. This is not a topic in all other IE versions greater 8 because there the version and the documentMode are the same.

Can you add this so that IE8 in compatibility mode shows version 8 and not 7? Currently the only way to workaround this is to additionally check the document.documentMode as well ...

**Comment by message** [comment]
Please attach an user agent for that case.

**Comment by faisalman** [comment]
Even if actually it's IE8, but when the user agent string states that it is IE7, then this library can't tell the otherwise. Furthermore, detecting whether the user agent is spoofed or not isn't something that this library want to achieve.. Thanks :+1:
