### ISSUE TITLE
Merge into global ua-parser project

### ISSUE THREAD

**Issue by bluesmoon** [faisalman/ua-parser-js#104]
Hey, it would be great if you could merge this code into the primary UA Parser project here: https://github.com/ua-parser to unify dev efforts.  The ua-parser project started out at Google as part of the [BrowserScope](http://www.browserscope.org/) project and both projects were opensourced.

It now has support for several languages including JavaScript, but I believe your project has some features that it lacks, for example, detecting the kind of device.

**Comment by Krinkle** [comment]
https://github.com/ua-parser/uap-ref-impl/issues/8

**Comment by faisalman** [comment]
In this library I try to experiment with a different approach where the size of regexes had to be optimized in such a way as to be acceptable in client-side scripts, which might not suit well with the scale as large as the size of ua-parser project..
