### ISSUE TITLE
Cant detect ie on windows 10 machines

### ISSUE THREAD

**Issue by mollases** [faisalman/ua-parser-js#105]
ua parser reports that IE is chrome

Microsoft added 'Edge/12.0' to their ua string, so that should be looked for
https://msdn.microsoft.com/en-us/library/ie/hh869301%28v=vs.85%29.aspx

```diff
-            /(trident).+rv[:\s]((\d+)?[\w\.]+).+like\sgecko/i                   // IE11
+            /(trident).+rv[:\s]((\d+)?[\w\.]+).+like\sgecko/i,                   // IE11
+            /(Edge)\/((\d+)?[\w\.]+)/i                   // IE11
```

**Comment by faisalman** [comment]
Hi @mollases , thank you for informing this, if you don't mind please submit a pull request to ua-parser-js/develop :grin:

**Comment by faisalman** [comment]
Fixed
