### ISSUE TITLE
Device undetected with Samsung s6 and Chome browser.

### ISSUE THREAD

**Issue by vingiarrusso** [faisalman/ua-parser-js#114]
```
{ ua: 'Mozilla/5.0 (Linux; Android 5.0.2; SM-G925T Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.111 Mobile Safari/537.36',
  browser: { name: 'Chrome', version: '42.0.2311.111', major: '42' },
  engine: { name: 'WebKit', version: '537.36' },
  os: { name: 'Android', version: '5.0.2' },
  device: { model: undefined, vendor: undefined, type: undefined },
  cpu: { architecture: undefined } }
```

It looks like chrome (possibly just this version?) omits 'SAMSUNG' before the model number in the UA string.  This makes the device show as undefined.  Forcing the UA to prefix the model with SAMSUNG gives device results as expected.

**Comment by mateeyow** [comment]
:+1:

**Comment by pieterhendrickx** [comment]
Same for S6 edge

Mozilla/5.0 (Linux; Android 5.1.1; SM-G925F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36

**Comment by mluyties** [comment]
Any idea on an ETA for this fix? This is an exceptionally popular phone right now... thanks.

**Comment by faisalman** [comment]
Please try again now in http://faisalman.github.io/ua-parser-js/ thanks :+1:
