### ISSUE TITLE
Troubles with some devices about `device`

### ISSUE THREAD

**Issue by kud** [faisalman/ua-parser-js#117]
UA: `Mozilla/5.0 (Linux; Android 5.0; SM-G900F Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.78 Mobile Safari/537.36`

I've got `undefined` on all properties on `device`.
---

List:
- [ ] Samsung S5
- [ ] Samsung S6

**Comment by dbcallan** [comment]
We have gotten this on many android devices as well.

**Comment by mateeyow** [comment]
:+1:

**Comment by RobinClowers** [comment]
I'm seeing the same problem with the S6, should I open a separate issue?

**Comment by kud** [comment]
@RobinClowers Fixed. :)

**Comment by faisalman** [comment]
Please try again now in http://faisalman.github.io/ua-parser-js/ thanks :+1:
