### ISSUE TITLE
Node version should return singleton.

### ISSUE THREAD

**Issue by Redsandro** [faisalman/ua-parser-js#118]
Every module that uses the parser needs to instantiate their own parser:

```
var UAParser = require('ua-parser-js');
var parser = new UAParser();
// do stuff with parser...
```

This is wasting some memory, because each module could share the same instance if `ua-parser-js` would return a singleton version of the parser, so that you can just do this:

```
var parser = require('ua-parser-js');
// do stuff with parser...
```

**Comment by ebbmo** [comment]
Hi,

I think that is a very valid point.
On the other hand I never (myself) initiate the parser more than once on our system. 
@Redsandro Why do you need to initiate it multiple times? And in the same environment?

KR, ebbmo

**Comment by Redsandro** [comment]
@ebbmo on different routes. Technically the `new ...` part could be in a separate custom module, but that would be working around a quirk. It's better to resolve the quirk.

(Slightly late response, not sure if this is still relevant.)
