### ISSUE TITLE
Is there a small typo in v0.7.8

### ISSUE THREAD

**Issue by macguffin** [faisalman/ua-parser-js#123]
Hi not sure but in the latest version in line 687:
|palm\sos

in version 0.7.7 it was:
|palm\os

Is this a typo or is it correct?
Thanks very much.

**Comment by demis-palma** [comment]
It's not a typo.
See https://github.com/faisalman/ua-parser-js/pull/120

**Comment by macguffin** [comment]
Ahh cool thanks just checking as I don't have this device to test on.

Thanks for the info. I'll close this.
