### ISSUE TITLE
[Nexus 6 + Chrome] Device Undetected

### ISSUE THREAD

**Issue by nilayk** [faisalman/ua-parser-js#128]
As seen in the screenshot, ua-parser-js does not identify the device (Nexus 6) running the latest Google Chrome 44.x

![screenshot_2015-08-03-13-06-54](https://cloud.githubusercontent.com/assets/278733/9046673/20800b48-39e1-11e5-9e38-6c84723db9fd.png)

**Comment by aamir** [comment]
I just encountered this as well, any eta on a fix?

**Comment by aamir** [comment]
Pull request https://github.com/faisalman/ua-parser-js/pull/133

**Comment by jlturner** [comment]
Hey @faisalman, can we merge this fix into master? Nexus 6 is a pretty popular device, and we'd like to not maintain a separate fork: https://github.com/faisalman/ua-parser-js/pull/133

**Comment by faisalman** [comment]
Fixed in #133
