### ISSUE TITLE
Android user agent

### ISSUE THREAD

**Issue by mathurs** [faisalman/ua-parser-js#132]
The following UA (Dalvik/2.1.0 (Linux; U; Android 5.1; Android SDK built for x86 Build/LKY45)) from mulator returns all the values in device to be undefined. I was planning to assume undefined to fallback as console but it seems thats not the case. Can you please help with what can be expected from device.type and if there can be a fallback for undefined values.

**Comment by faisalman** [comment]
Unfortunately no, as `undefined` can means anything without extra information..
