### ISSUE TITLE
is*() utility methods

### ISSUE THREAD

**Issue by debuti** [faisalman/ua-parser-js#135]
Nice project, anyway it would be nice to have methods like 
bool isLinux()
bool is32b()
and so

**Comment by faisalman** [comment]
Hi debuti, thanks for the idea, so far I have no plan to add new methods. For that purpose, I found this project to be useful: https://github.com/rossnoble/ua-parser-js-helpers

**Comment by faisalman** [comment]
Since version `2.0.0` you can use `is()`[^1]:

```js
getOS().is('Linux');
getCPU().is('arm64');
```

[^1]: https://docs.uaparser.dev/api/main/idata/is.html
