### ISSUE TITLE
Meteor package not working?

### ISSUE THREAD

**Issue by jiku** [faisalman/ua-parser-js#137]
I can't seem to access the UAParser object on the client. It always returns undefined, whether I use setUA or not. You can see [this](http://meteorpad.com/pad/iq9RdbNB2mGdPuKpk/ua-parser-js) MeteorPad for examples of what I've tried. Any ideas? (FYI switched to feature detection (Modernizr and @supports), so don't look into on my account!)

**Comment by spaeth** [comment]
I have the same problem.

**Comment by Krabaul** [comment]
+1

**Comment by pdazcom** [comment]
+1 same question

**Comment by andykingking** [comment]
+1

**Comment by surenyonjan** [comment]
+1

UAParser is undefined

**Comment by pakoGit** [comment]
+1
Meteor 1.4.3.2

**Comment by faisalman** [comment]
Moving the discussion in this thread to #223
