### ISSUE TITLE
Doesn't recognize Samsung tablet

### ISSUE THREAD

**Issue by Rob-ot** [faisalman/ua-parser-js#143]
Doing getDevice() on the user agent 

`Mozilla/5.0 (Linux; Android 4.4.2; SM-T230NU Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36`

should give `{model: 'SM-T230NU', type: 'tablet', vendor: 'Samsung'}`

but gives `{model: undefined, type: undefined, vendor: undefined}`

Manually running the user agent against the regex on this line https://github.com/faisalman/ua-parser-js/blob/master/src/ua-parser.js#L553 does match but this regex doesn't appear to be tested in the normal flow of getDevice().

**Comment by vkarampinis** [comment]
Check here: http://faisalman.github.io/ua-parser-js/

**Comment by Rob-ot** [comment]
Ah hah! I was using an outdated npm package (user-agent-parser) instead of ua-parser-js. I'll ping the maintainer of the outdated lib and ask them to put up a deprecated message or something.

Thanks for the help and for making this extremely useful libaray!
