### ISSUE TITLE
General Android smartphones should be detected as mobile

### ISSUE THREAD

**Issue by lquinn** [faisalman/ua-parser-js#146]
I'm using Chrome on a new Android smartphone where the User-Agent is

Mozilla/5.0 (Linux; Android 5.1.1; STV100-3 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36

UAParser.js does not currently detect this as a mobile device, which has caused this smartphone to get Flash content from a popular Web site.

UAParser.js has a fallback for unidentifiable devices, but the check is too specific in that it only matches a Firefox style of User-Agent. It would be better to generalize the check so that any User-Agent that includes "Mobile" would be categorized as a mobile device.

This would help future-proof UAParser.js to handle new Android smartphones.

**Comment by lquinn** [comment]
Pull request #145 would fix this.

**Comment by lquinn** [comment]
@faisalman, can you merge #145? It would also address issue #117 and would generally make UAParser.js more robust to new Android smartphones.

**Comment by faisalman** [comment]
Merged in #145

More references can be found in:
https://developer.chrome.com/multidevice/user-agent
https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference
