### ISSUE TITLE
No support for ios-firefox

### ISSUE THREAD

**Issue by korvin101** [faisalman/ua-parser-js#152]
![3a79fc3c-8a1a-11e5-9ca7-6d9cad3f8d37](https://cloud.githubusercontent.com/assets/3283023/11167777/2d483b26-8bac-11e5-88c2-511e86ae6139.jpg)

**Comment by dd1994** [comment]
大哥说英文啊，作者看不懂中文的...

**Comment by korvin101** [comment]
@dd1994 已更新，感谢提醒

**Comment by faisalman** [comment]
This was fixed in #151, will be pushed in next version ;)
