### ISSUE TITLE
deviceType is undefined for most devices.

### ISSUE THREAD

**Issue by lrvick** [faisalman/ua-parser-js#16]
deviceType should always be populated with tablet/tv/desktop/mobile as appropriate. It is one of, if not the most important thing to check against for general layout choices and should almost never be undefined, imo.

Perhaps consider incorporate some of the matching ideas from https://github.com/bjankord/Categorizr ?

Currently I am having to use the device regex block from Categorizr to consistently provide deviceType and ua-parser-js for everything else.

**Comment by dbcallan** [comment]
Categorizr is no longer being maintained, is there any other option?  We need Device type badly for our project.

Thanks.
