### ISSUE TITLE
Firefox on iOS reports browser as Safari

### ISSUE THREAD

**Issue by zspitzer** [faisalman/ua-parser-js#166]
But Chrome reports as Chrome, the UA string contains FxiOS/2.0

makes life challenging when trying to work around WkWebView limitations

**Comment by faisalman** [comment]
Do you have the complete UA string? should've been fixed in #151

**Comment by zspitzer** [comment]
iPad	Mozilla/5.0 (iPad; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) FxiOS/1.0 Mobile/12F69 Safari/600.1.4

https://developer.mozilla.org/en-US/docs/Web/HTTP/Gecko_user_agent_string_reference
