### ISSUE TITLE
Device detect incorrect

### ISSUE THREAD

**Issue by TooBug** [faisalman/ua-parser-js#168]
```
Mozilla/5.0 (Linux; U; Android 5.1; zh-cn; m2 note Build/LMY47D) AppleWebKit/533.1 (KHTML, like Gecko)Version/4.0 MQQBrowser/5.4 TBS/025489 Mobile Safari/533.1 MicroMessenger/6.3.13.49_r4080b63.740 NetType/cmnet Language/zh_CN
```

This is an Android phone with flyme5 (based on Android 5.1), the brand is Meizu(which in readme) and model is `Meilan Note 2` or just `M2 Note`. But the result of `device` is empty.

**Comment by nikhilmotiani** [comment]
same is the case with the following UserAgent *UserAgent Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36*

This is for Samsung Galaxy Tablet. And the result is as below
`{"ua":"UserAgent Mozilla/5.0 (Linux; Android 4.4.2; Android SDK built for x86 Build/KK) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36","browser":{"name":"Chrome","version":"30.0.0.0","major":"30"},"engine":{"version":"537.36","name":"WebKit"},"os":{"name":"Android","version":"4.4.2"},"device":{},"cpu":{}}`

**Comment by nmaves** [comment]
I think we are seeing this with the default "Internet" application/browser on Samsung devices.

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG-SM-G925A Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

This library shows it as Chrome but it is definitely not Chrome.

**Comment by xiaoDC** [comment]
`mozilla/5.0 (linux; android 5.1; vivo x6d build/lmy47i) applewebkit/537.36 (khtml, like gecko) version/4.0 chrome/37.0.0.0 mobile mqqbrowser/6.9 tbs/036902 safari/537.36 micromessenger/6.3.32.960 nettype/wifi language/zh_cn`

but the device.type sometime is 'mobile', sometime is undefined.

**Comment by faisalman** [comment]
To keep this issue tracker on the track, if you have different type of case please open a new issue in separate thread, thanks :+1:
