### ISSUE TITLE
Any chance new stable release soon ? 

### ISSUE THREAD

**Issue by idans-ybrantdigital-com** [faisalman/ua-parser-js#169]
Have new models/devices been incorporated into your code since the latest 0.7.10 release ?

Appreciate your hard work,

Thanks :)

**Comment by guilhas** [comment]
I am using master with success. But yes it would be nice to have something official.

**Comment by faisalman** [comment]
Hi @idans-ybrantdigital-com thanks, I have a plan to release a new version soon but not yet a stable release..

duplicate #192
