### ISSUE TITLE
issue on surface 

### ISSUE THREAD

**Issue by wonskarol** [faisalman/ua-parser-js#170]
I get some problems using your lib on Microsoft Surface device (with IE 11. 0.9600.17031 on board).

```
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/UAParser.js/0.7.10/ua-parser.js"></script>
</head>
<body>
</body>
<script>
    (function() {
        var parser = new UAParser();
        console.log(parser.getResult());
    })();
</script>
</html>
```

running this page on Surface gives an error: `'UAParser' is undefined`
On Chrome (desktop), Safari (iphone) and IE11 (desktop) everything works like a charm.

**Comment by faisalman** [comment]
Any thoughts why?
