### ISSUE TITLE
IE device details, show type as tablet

### ISSUE THREAD

**Issue by motianinikhil** [faisalman/ua-parser-js#174]
I am using IE 11.0.9600 on Windows 8.1
User Agent String - 

> Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; GWX:MANAGED; rv:11.0) like Gecko

`{
  "ua": "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; GWX:MANAGED; rv:11.0) like Gecko",
  "browser": {
    "name": "IE",
    "version": "11.0",
    "major": "11"
  },
  "engine": {
    "version": "7.0",
    "name": "Trident"
  },
  "os": {
    "name": "Windows",
    "version": "8.1"
  },
  "device": {
    "type": "tablet"
  },
  "cpu": {
    "architecture": "amd64"
  }
}`

**Comment by nikhilmotiani** [comment]
@faisalman Any updates on this issue?

**Comment by grossmail1** [comment]
we are still having this issue in 0.7.10

**Comment by yurieastwood** [comment]
Latest release (8 months ago) still has the problem. Any updates?
