### ISSUE TITLE
Error ocurred when a custom method is added to Array Object.

### ISSUE THREAD

**Issue by Alex-Ayala-Bonilla** [faisalman/ua-parser-js#177]
I have been using this parser, and recently  I have added this line in my application
`Array.prototype.contains` = function(it) { return this.indexOf(it) != -1 ;};`
After that, I have this error:

```
UbiquaRS TypeError: str1.toLowerCase is not a function
    at Object.util.has \node_modules\user-agent-parser\src\ua-parser.js:41:52)
```

The error is for use `for in loop` instead of `for (var j=0; j< ...)`

``` javascript
for (var j in map[i]) {
                        if (util.has(map[i][j], str)) {
```

I think would be better do not use `for in loop` to avoid this errors. 

Thanks.

**Comment by faisalman** [comment]
`for (var j in map[i]) {` wasn't used anymore now.. Thanks :+1:
