### ISSUE TITLE
OS is undetected from the following user agent strings

### ISSUE THREAD

**Issue by UKNC** [faisalman/ua-parser-js#178]
- SAMSUNG-GT-C3303/C3303XXJG5 NetFront/4.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)
-  Nokia-MIT-Browser/3.0
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)
-  UCWEB/2.0 (MIDP-2.0; U; Adr 5.0.2; en-US; SM-A300FU) U2/1.0.0 UCBrowser/10.1.4.573 U2/1.0.0 Mobile
-  SonyEricssonW660i/R8BB Browser/NetFront/3.3 Profile/MIDP-2.0 Configuration/CLDC-1.1
-  UCWEB/2.0 (MIDP-2.0; U; zh-CN; Lenovo A7000-a) U2/1.0.0 UCBrowser/3.4.3.532  U2/1.0.0 Mobile
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)
-  UCWEB/2.0 (MIDP-2.0; U; Adr 4.1.2; unli.smart.com.ph; EK-GC100) U2/1.0.0 UCBrowser/9.8.0.534 U2/1.0.0 Mobile
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)
-  MAUI WAP Browser
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)
-  Microsoft Pocket Internet Explorer/0.6
-  Mozilla/5.0 (PlayStation 4 3.50) AppleWebKit/537.78 (KHTML, like Gecko)

**Comment by faisalman** [comment]
Any information about what is the correct OS for each of those user agent strings? please open separate issues for different cases.. Thanks :+1:
