### ISSUE TITLE
error!

### ISSUE THREAD

**Issue by xgqfrms** [faisalman/ua-parser-js#183]
> https://raw.githubusercontent.com/faisalman/ua-parser-js/master/src/ua-parser.min.js

![ bug.png](https://raw.githubusercontent.com/xgqfrms/HTML5/master/images/bug.png)

@faisalman 

http://plugins.jquery.com/ua-parser-js/
![ de.png](https://raw.githubusercontent.com/xgqfrms/HTML5/master/images/de.png)

**URL error!**

**Comment by ckyambitny** [comment]
xD
