### ISSUE TITLE
[minor] Doesn't identify Nexus 6P

### ISSUE THREAD

**Issue by au5ton** [faisalman/ua-parser-js#185]
The useragent of my [Huawei Nexus 6P](https://www.google.com/nexus/6p/) is:
`Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6P Build/MTC19V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537`

However, us-parser-js recognizes this as a Motorola Nexus 6. No big deal, but I thought it'd be worth reporting.

**Comment by danywheeler** [comment]
you cloud write you own regex to extend support, we don't need the code to contain all device !
