### ISSUE TITLE
Does not work with requirejs?

### ISSUE THREAD

**Issue by steffchep** [faisalman/ua-parser-js#187]
I have the following: 

```
require(['jquery', 'ua-parser'], function($, UAParser) {
    console.log(UAParser);
});

```

and I get "undefined" in the log output. The script does get loaded according to the network window.
I downloaded ua-parser.min.js from the dist - is there anything else I need?

**Comment by chalchis** [comment]
![2016-09-09_09h20_20](https://cloud.githubusercontent.com/assets/2206648/18390161/b5afa78a-766e-11e6-9af8-e0aac45ef76d.png)

**Comment by steffchep** [comment]
Yes, I've got the require paths, and I can see in the network pane that the files are all loaded. 
But the UAParser object is not available.
I don't see a fundamental difference between the example posted any my question?

Yes, it gets hooked into jquery automatically ($.ua), and this works in my case,  but according to the documentation, the UAParser Object should still be available for use outside of jquery, but it is not.

**Comment by andrewblaney** [comment]
+1

Also having this problem using require('ua-parser-js') and browserify.
