### ISSUE TITLE
Windows Server 2003 is detected as Windows XP

### ISSUE THREAD

**Issue by Spirit-Sound** [faisalman/ua-parser-js#193]
Windows Server 2003 is detected as Windows XP.

User-Agent: Opera/12.0(Windows NT 5.2;U;en)Presto/22.9.168 Version/12.00

Windows NT 5.1 - XP
Windows NT 5.2 - Server 2003

Okay?

**Comment by demoneaux** [comment]
As per [this archived page from Microsoft Developer Network](http://web.archive.org/web/20081122053950/http://msdn.microsoft.com/en-us/library/ms537503(VS.85).aspx), NT 5.2 can represent both Windows Server 2003 and Windows XP 64-bit version.

**Comment by faisalman** [comment]
Unless there is a phrase that can distinguish between those two, I'm afraid I can't fix this currently.. If you have any solution please submit here :+1: Thanks
