### ISSUE TITLE
Ubuntu 16.04 LTS and Fedora 24 can't return version (undefined)

### ISSUE THREAD

**Issue by xmuplus** [faisalman/ua-parser-js#194]
And please add [`Manjaro Linux`](https://manjaro.github.io/) in os names. It's based on Arch, but cannot be detected as Arch.

**Comment by faisalman** [comment]
Hi xmuplus, do you have an example of user agent string that can be referred as from Manjaro?

**Comment by xmuplus** [comment]
Linux x64

**Comment by faisalman** [comment]
No, I mean, what's the user agent of the browser in manjaro?

**Comment by xmuplus** [comment]
You mean Firefox (for Manjaro) 49.0.2?

**Comment by faisalman** [comment]
Yes, or any browser that contains `manjaro` phrase maybe?

**Comment by xmuplus** [comment]
It's still detected as `Linux x64` on Chrome 54.0.2840.90 (64-bit) in Manjaro.

**Comment by faisalman** [comment]
Can you post a screenshot of http://faisalman.github.io/ or the result of `getResult()`? otherwise I can't seem to know what the user agent string is..

**Comment by xmuplus** [comment]
ua: "Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0"
