### ISSUE TITLE
Windows 2000 interpreted as Windows "version" 2000

### ISSUE THREAD

**Issue by p4d** [faisalman/ua-parser-js#198]
Hello,

i'm using your parser in order to check wether the user is valid or not depending on his os version and browser. The problem is a light one (i made an adjustement to solve it) but you might be interested to know it : When Windows 2000 is used, the result.os.name is well found (Windows) but the version is 2000 which is not really the case.. 2000 in that case is the year of production, the version should be Windows NT 5.0, so 5.0 would do the trick. Thanks for your tool, it is classy !

**Comment by faisalman** [comment]
Hi, yes it is the intended behavior of this lib, in which the version number is being translated to it's version name
