### ISSUE TITLE
REGRESSION (0.7.12): Android Chrome returns wrong version number

### ISSUE THREAD

**Issue by jensenharris** [faisalman/ua-parser-js#202]
User agent `Mozilla/5.0 (Linux; Android 4.4; Nexus 5 Build/_BuildID_) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36` used to return Chrome version 30.

Starting with 0.7.12, now it returns version 4.

**Comment by faisalman** [comment]
Since version `0.7.12`, every chrome browser which contains `version/x.x` is now identified as stock android browser instead of chrome. See https://github.com/faisalman/ua-parser-js/commit/2467a458e337cdab086d6d3bc58c1ad041ea07d5#diff-c70baca548c690f3c8d27a36d87a5f18R13
