### ISSUE TITLE
Feature request: isBrowser

### ISSUE THREAD

**Issue by kucherenkovova** [faisalman/ua-parser-js#203]
Would be nice to have function that simply tells you if user agent is a browser or not.  
(similar to #156)

**Comment by kucherenkovova** [comment]
If you're open to contributions and think that this might be a good feature I'm going to make a PR closing this issue.

**Comment by zentuit** [comment]
That sounds like a good addition to https://github.com/rossnoble/ua-parser-js-helpers

**Comment by faisalman** [comment]
Hi @kucherenkovova, I'm all open for contributions but I try to be selective when adding new features to keep the balance between the level of usefulness and simplicity. 

Furthermore, I'm still not sure whether to include detection of any other agent types beside browser (like media player, for example, https://github.com/faisalman/ua-parser-js/blob/master/src/ua-parser.js#L340) or not in the meantime. 

So in this case, until I changed my mind, you can still contribute by creating a helper on top of this library as suggested by @zentuit.
