### ISSUE TITLE
os.version returns 8.1 instead of 2012 R2 for Windows

### ISSUE THREAD

**Issue by ssougnez** [faisalman/ua-parser-js#204]
Hi,

as said in the title, I'm currently using Windows 2012 R2 and when I call "getResult().os.version", it returns me "8.1" instead of "2012 R2".

Thanks

Regards

**Comment by faisalman** [comment]
Any idea on how to distinguish them?

**Comment by ssougnez** [comment]
Hello,

I don't have any Windows 8 available but here is the user agent for Windows 2012:

"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

Now, I did a small research on Google and find this: https://www.labnol.org/software/windows-8-ie-user-agent-string/20965/ and http://graphicmaniacs.com/note/windows-8-user-agent-string/

In these articles, it seems that Windows 8 is "Windows NT 6.2" while Windows 2012 is "Windows NT 6.3" but according to https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx, "Windows NT 6.3" = "Windows 8.1"... 

Maybe displaying Windows 8 for Windows 2012 is the best solution as most of the time, end users will more likely have 8 than 2012.

**Comment by faisalman** [comment]
Ok, closing this for now
