### ISSUE TITLE
Undefined values for iOS apps

### ISSUE THREAD

**Issue by tmosmant** [faisalman/ua-parser-js#206]
We have an iOS app that creates a default user agent as `AppName/version CFNetwork/version Darwin/version`. Would it be possible for you to parse it?

Currently I'm stuck with this:

![image](https://cloud.githubusercontent.com/assets/3709742/21006912/3cf4a304-bd3b-11e6-9682-b1de8f1e17b9.png)

**Comment by faisalman** [comment]
No pattern for that already but you can push this limitation by creating your own regex pattern and then pass it as a parameter. For example:

```js
var str = "AppName/version CFNetwork/version Darwin/version";
var rgx1 = [[/(appname)\/([\w\.]+).+cfnetwork.+darwin/i], 
            [UAParser.BROWSER.NAME, UAParser.BROWSER.VERSION]];
var rgx2 = [[/appname.+cfnetwork\/(\w).+darwin/i], 
            [UAParser.OS.VERSION, [UAParser.OS.NAME, 'iOS'] ]];

var ua = UAParser(str, { browser : rgx1, os : rgx2 });
console.log(ua.browser); // { name:'AppName', version:'version'}
console.log(ua.os); // { name:'iOS', version:'v' }
```

See https://github.com/faisalman/ua-parser-js#extending-regex-patterns

**Comment by tmosmant** [comment]
It seems to be a common behavior between iOS apps. Would you consider a pull request on this?
