### ISSUE TITLE
Monitor change

### ISSUE THREAD

**Issue by jlouazel** [faisalman/ua-parser-js#209]
Is it possible to add a CHANGELOG.md or at least to draft more specific messages into Github releases than `Build dist package`?

It will help us follow more easily updates of the project.

Thanks 👍

**Comment by faisalman** [comment]
That would be great :+1:

**Comment by jlouazel** [comment]
@faisalman I think a CHANGELOG is good idea. We will have to track changes from the beginning to make it complete but it's not a big deal since we only have 29 releases. If you don't mind, I think I'll start a PR to go further with it. You'll be able to help me on it.
