### ISSUE TITLE
Missing browser for Samsung Android device

### ISSUE THREAD

**Issue by nmaves** [faisalman/ua-parser-js#211]
The default internet browser for Samsung Android devices is an application called "Internet". For the user agent string bellow I would suggest adding a new browser called "Samsung Internet".

User agent string

`Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG-SM-G925A Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`

**Comment by mrmckeb** [comment]
This is currently detected as Android Browser from my tests, which does allow one to differentiate from Chrome - but isn't as accurate as targeting that browser by name.
