### ISSUE TITLE
User Agent Errors

### ISSUE THREAD

**Issue by ZoltanSimon** [faisalman/ua-parser-js#214]
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/534.57.2 (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2

For this user agent, it says that we are using Windows 8, while we are using Windows 10 for the test. 

Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-P601 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Safari/537.36

This was shown to be a mobile, but in fact it’s a tablet.

**Comment by faisalman** [comment]
Hi, please describe each issue specifically as a new issue..
