### ISSUE TITLE
iOS QQ browser detected as "WebKit".

### ISSUE THREAD

**Issue by hifall** [faisalman/ua-parser-js#215]
The user agent string is:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Mobile/14B100 QQ/6.6.2.408 V1_IPH_SQ_6.6.2_1_APP_A Pixel/640 Core/UIWebView NetType/WIFI

It should give QQ Browser, instead, it gives WebKit, which is not correct.

**Comment by ebbmo** [comment]
Hi @hifall,

Good point. Do you mind to open a PR for this recognition (including tests?)

KR, ebbmo

**Comment by faisalman** [comment]
Fixed in #222
