### ISSUE TITLE
NPM version appears to be out of date

### ISSUE THREAD

**Issue by nickforddesign** [faisalman/ua-parser-js#217]
The version I just installed with npm appears to be 0.6.0, and doesn't support AMD correctly.

**Comment by nosovk** [comment]
got 0.7.12 from NPM today. Could close an issue or now.

**Comment by nickforddesign** [comment]
Confirmed, thanks

**Comment by simison** [comment]
This package is likely causing the confusion: https://www.npmjs.com/package/user-agent-parser

It points to this repository:

![image](https://user-images.githubusercontent.com/87168/29479520-4f2e5d64-847b-11e7-9992-c6028624a24f.png)

Is @mattmueller a maintainer in this repository anymore?
