### ISSUE TITLE
parse ua incorrectly

### ISSUE THREAD

**Issue by khowarizmi** [faisalman/ua-parser-js#219]
Mozilla/5.0 (Linux; Android 6.0.1; SM-C5000 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 wkbrowser 4.1.35 3065

it is supposed to get `device.model == sm-c5000` , `device.vendor == samsung` 

but ua-parser-js tell me `device.model == Xperia Phone` , `device.vendor == Sony`

**Comment by ebbmo** [comment]
Hi @khowarizmi,

Good point! You're definitely right!
Would you mind opening a PR for it?

KR, ebbmo
