### ISSUE TITLE
UCBrowser is incorrectly identified as Chrome

### ISSUE THREAD

**Issue by jnoring** [faisalman/ua-parser-js#220]
User agent: `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 UBrowser/5.6.12860.7 Safari/537.36`

**Comment by jnoring** [comment]
Note there's a similar defect filed in a separate library filed here: https://github.com/browscap/browscap/issues/920 - need to also look for `UBrowser` string

**Comment by VeeteshJain** [comment]
ua parser is not able to detect UC browser.
for UC browser 
```Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; XT1635-02 Build/MPN24.104-56) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.0.915 U3/0.8.0 Mobile Safari/534.30```

for UC browser mini
```Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; XT1635-02 Build/MPN24.104-56) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1 UCBrowser/10.7.9.856 Mobile```

**Comment by ebbmo** [comment]
Hey guys,

I am a bit confused. Is it **UBrowser** or is it **UCBrowser**? Or both?
**Plus**: Either way, I think you are right that this should be detected accordingly. 

Therefore: Do you mind opening a Pull Request?

KR, ebbmo
