### ISSUE TITLE
Edge browser version detected incorrectly

### ISSUE THREAD

**Issue by hash1492** [faisalman/ua-parser-js#232]
Hi, 

Here is my user agent string:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
```
The actual edge version of this is ```Microsoft Edge 38.14393.0.0``` and ```Microsoft EdgeHTML 14.14393```

But ua-parser-js is detecting the browser version as "14.14393", which is incorrect.

Please fix it.

**Comment by mrmckeb** [comment]
How would one know this from the UA, @hash1492? And isn't the EdgeHTML version enough? That's what caniuse.com uses.

**Comment by ebbmo** [comment]
Hi @hash1492,

Looking at http://www.useragentstring.com/index.php using your UA, the result is 14.1... as well for the "Edge Version". 
So the question from @mrmckeb remains: How would you find out which Edge version it is from your provided user agent?
And based on your user agent: What would you expect instead?

KR,
ebbmo

**Comment by faisalman** [comment]
Closing this for now
