### ISSUE TITLE
Including email clients?

### ISSUE THREAD

**Issue by bradvogel** [faisalman/ua-parser-js#237]
I noticed this library isn't parsing user agents for email clients. Would you be open to us submitting PRs to handle them?

One example:
```
$ node
> var parser = require('ua-parser-js');
undefined
> parser('Microsoft Office/16.0 (Microsoft Outlook Mail 16.0.8104; Pro)')
{ ua: 'Microsoft Office/16.0 (Microsoft Outlook Mail 16.0.8104; Pro)',
  browser: { name: undefined, version: undefined, major: undefined },
  engine: { version: undefined, name: undefined },
  os: { name: undefined, version: undefined },
  device: { model: undefined, vendor: undefined, type: undefined },
  cpu: { architecture: undefined } }
> 
```

More:
`Spark/1.7.3.948 CFNetwork/811.4.18 Darwin/16.5.0	`
`Superhuman`
`Airmail%203/420 CFNetwork/811.4.18 Darwin/16.5.0 (x86_64)`

**Comment by ebbmo** [comment]
Hi bradvogel,

I think this would be great! 
Based on this site: http://thadafinser.github.io/UserAgentParserComparison/v5/user-agent-detail/aa/82/aa82eef8-8f4d-4f60-b6c5-dc7a477666f0.html there are currently 2 things that can be derived (by some parsers):
- The Browser name is "Outlook 2016"
- The device type is "Desktop"

I can follow the outlook 2016 part, but i'm not sure how other parsers come up with "Desktop".
In addition the browser version could be added (here: 16.0.8104)

What do you think?

**Comment by bradvogel** [comment]
I think "Microsoft Office" is always Desktop.

**Comment by ebbmo** [comment]
Are you certain? 
I haven't tested any MS Apps on Android or iPhone, so I don't what kind of UA they send when I click on a link there... They could be using an InApp Browser like Facebook too, and that may as well contain MS Office... Do you have a way of testing it?

**Comment by bradvogel** [comment]
No, I'm not. I unfortunately don't have an easy way to test

**Comment by ebbmo** [comment]
Ok. So there is a bit of "Google" involved to find out whether your assumption is correct ;)
Do you mind to open a PR for the MS Outlook recognition?

KR, ebbmo

**Comment by markb-trustifi** [comment]
Please check also Outlook Client for MacOS, its browser type is shown as "Webkit/603.3.8".

**Comment by glennzw** [comment]
Just wondering if any progress has been made on this? It'd be good to also parse Office versions too.

### e.g 1 Outlook user agent:

```
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Microsoft Outlook 16.0.9126; Microsoft Outlook 16.0.9126; ms-office; MSOffice 16)
```

ua-parser-js: `IE 7 on Windows 10`
whatismybrowser.com: `Outlook 16 on Windows 10`

<hr>

### e.g 2 MS Word user agent:
```Microsoft Office/16.0 (Windows NT 10.0; Microsoft Word 16.0.11001; Pro)```

ua-parser-js: `Unknown on Windows 10`
whatismybrowser.com: `Word 16 on Windows 10`

**Comment by faisalman** [comment]
```js
import { UAParser } from 'ua-parser-js';
import { Emails } from 'ua-parser-js/extensions';

const userAgent = 'Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Thunderbird/78.13.0';
const emailParser = new UAParser(Emails);
const result = emailParser.setUA(userAgent).getResult();

console.log(result.browser.type); // email
console.log(result.browser.name); // Thunderbird
```
