### ISSUE TITLE
No way to know whether I am using a browser simulator in laptop or using actual device

### ISSUE THREAD

**Issue by maaizelahi** [faisalman/ua-parser-js#238]
No way yo know whether I am using a browser simulator in laptop or using actual device

**Comment by faisalman** [comment]
Since we just rely on user agent info only, quite certainly, yes, no way..

**Comment by ebbmo** [comment]
Could be closed imo. The ua-parser does what it says: it analyses the UserAgent. And since that can be faked by a simple bash command there is now way of telling...

**Comment by faisalman** [comment]
Yep, closing this
