### ISSUE TITLE
GetDeviceType Method

### ISSUE THREAD

**Issue by atardadi** [faisalman/ua-parser-js#244]
Hi,

I think it would be super helpful to add a method getDeviceType which can return 'desktop', 'tablet' or 'mobile' #

**Comment by Redmega** [comment]
From the docs:
```
getDevice()
returns { model: '', type: '', vendor: '' }

# Possible 'device.type':
console, mobile, tablet, smarttv, wearable, embedded
```

**Comment by faisalman** [comment]
Hi @atardadi, as already pointed out by @Redmega, you can use the `getDevice()` method: 

```js
var myUA = 'Android 4.4; C1905 Build/15';
var myDevice = new UAParser(myUA).getDevice();

console.log(myDevice.type); // mobile
```

Is there any specific reason why we need to make it as a new method?

**Comment by bdkent** [comment]
Is the assumption `!myDevice.type` is `'desktop'`?

**Comment by faisalman** [comment]
I think it's more like `unknown` device.. Although it has a possibility to be a `desktop` but I prefer to not generalize it in a single `desktop` category.. It's more safe to leave the interpretation of `unknown` and how to handle it to the user instead..

**Comment by faisalman** [comment]
Closing this for now
