### ISSUE TITLE
Add 'Blink' as detectable rendering engine

### ISSUE THREAD

**Issue by brianchirls** [faisalman/ua-parser-js#246]
Chrome has been off WebKit and using its own fork Blink for some time now, since v28.

I understand there are two ways to detect Blink, though I'm not sure how reliable they are:
- `/Chrome\/[0-9\.]+/` - see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#Rendering_engine)
- `/WebKit\/537\.36/` - This one *mostly* seems to check out, per this [Chrome Version History](https://en.wikipedia.org/wiki/Google_Chrome_version_history), except for Chrome 27, which actually used WebKit 537.36.

It's worth mentioning that Chrome on iOS still uses WebKit.

**Comment by brianchirls** [comment]
It looks like the version number for Blink never progresses beyond 537.36, so it might make sense to just report whatever the Chrome version number is.

**Comment by mrkishi** [comment]
What about reporting Chrome >= 28 as Blink?

Perhaps something along these lines:
```js
[/(chrome)\/((?:2[89]\.|[3-9]\d\.|\d{3}\.)[\w\.]+)/i, [[NAME, 'Blink'], [VERSION]]
```

I _think_ it'd work fine for most Chromium-based browsers, too.
