### ISSUE TITLE
Add Oculus Browser

### ISSUE THREAD

**Issue by brianchirls** [faisalman/ua-parser-js#247]
Here's a sample user agent string:
`Mozilla/5.0 (Linux; Android 7.0; SM-G920I Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) OculusBrowser/3.4.9 SamsungBrowser/4.0 Chrome/57.0.2987.146 Mobile VR Safari/537.36`

Now this gets reported as Android Browser 4.0, but it should be Oculus Browser 3.4.9, running Blink 57.0.2987 (see #246). Device and OS info are correct.

**Comment by ebbmo** [comment]
Hi brianchirls,
Good find - do you mind open a PR for it (tests included)?
KR, ebbmo

**Comment by brianchirls** [comment]
Sure. I was able to get it working as an extension, so I don't think it would be too much trouble to make a PR.

**Comment by ebbmo** [comment]
Perfect! :)
