### ISSUE TITLE
Error in UC browser detection

### ISSUE THREAD

**Issue by thamsrang** [faisalman/ua-parser-js#256]
Hi,
For below UA the parser returns the browser as **Android Browser**, but actually it an **UC Browser**.

**Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; SM-T355Y Build/MMB29M) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.3.8.976 U3/0.8.0 Mobile Safari/534.30**

**Comment by faisalman** [comment]
Hi, which version of UAParser do you use?

**Comment by thamsrang** [comment]
I used your website to parse the UA.
http://faisalman.github.io/ua-parser-js/

**Comment by thamsrang** [comment]
Sorry Faisalman. I have checked with latest version. Its works fine.

**Comment by faisalman** [comment]
Ah yes, I'll roll a new patch soon.. Thanks :+1:

**Comment by ilionic** [comment]
Got an error with this new version, reverted to previous.
```
TypeError: regex[(j++)].exec is not a function
    at Browser.rgx (/node_modules/ua-parser-js/src/ua-parser.js:105:42)
    at UAParser.getBrowser (/node_modules/ua-parser-js/src/ua-parser.js:913:24)
    at UAParser.getResult (/node_modules/ua-parser-js/src/ua-parser.js:936:32)
    at UAParser (/node_modules/ua-parser-js/src/ua-parser.js:901:55)
```
