### ISSUE TITLE
Not supported for Redmi devices!

### ISSUE THREAD

**Issue by nikunjdnp** [faisalman/ua-parser-js#260]
Hi,
I am getting undefined for Redmi devices. 

`device: Device { vendor: undefined, model: undefined, type: 'mobile' },`
`cpu: CPU { architecture: undefined }`

**Comment by shukla2009** [comment]
+1

**Comment by faisalman** [comment]
I'm a Redmi user too, it's detected just fine here.. What's your UA?

**Comment by shukla2009** [comment]
Mozilla/5.0 (Linux; Android 5.1; MI PAD 2 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Safari/537.36 [FB_IAB/FB4A;FBAV/137.0.0.24.91;]

**Comment by nikunjdnp** [comment]
Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

**Comment by arunrreddy** [comment]
@faisalman I think this regex would probably work for most of the Redmi devices. With a few tweaks, it can probably be made to work for Mi pad devices as well. 
`/android.+(redmi[\s\-_]*(?:note)?(?:[\s_]*[\w\s]+))\s+build/i`

**Comment by faisalman** [comment]
Fixed in #264, thanks @arunrreddy
