### ISSUE TITLE
[Suggestion] Use only MIT license

### ISSUE THREAD

**Issue by rprata** [faisalman/ua-parser-js#266]
Hi, 
I check your project, but I am confused about the license. Why that you use GPLv2 for this project? Is it not better to keep only MIT License, according your text license description? 

Best regards,

**Comment by pinty** [comment]
As I understand from the license text, this project is dual licensed under GPLv2 / MIT. You can chose from those two which one suits you the most.
Can the author confirm this?
Thank you!

**Comment by faisalman** [comment]
@rprata as the original author, I simply want to give more flexibility for people who want use this work, either under a restrictive license (GPL) or a permissive one (MIT). Thus, as pointed by @pinty it's dual-licensed under GPLv2 / MIT. Feel free to choose which one you might prefer.

Related: #1

**Comment by rprata** [comment]
Ok, thank you for the answer.
