### ISSUE TITLE
Last Chrome on Windows 10 fails to parse getDevice()

### ISSUE THREAD

**Issue by RUSSCITY** [faisalman/ua-parser-js#275]
When I trying to parse device from my user agent I get undefined. Last Chrome.

My user agent: `navigator.userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"`

Trying: `uAParser.setUA(navigator.userAgent).getDevice()`
Result: `{vendor: undefined, model: undefined, type: undefined}`

**Comment by faisalman** [comment]
I think the result is as expected, since the user agent string contains no info that can be related to device
