### ISSUE TITLE
Incorrect device type of MI 5

### ISSUE THREAD

**Issue by avdeev** [faisalman/ua-parser-js#282]
UA: __Mozilla/5.0 (Linux; Android 6.0.1; MI 5 Build/MXB48T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36__

```
{ vendor: 'Xiaomi', model: 'MI 5', type: 'tablet' }
```

Correct - mobile

**Comment by loris** [comment]
Confirm the same issue, it should type it as `mobile`

**Comment by avdeev** [comment]
Fixed in #285

**Comment by loris** [comment]
Thanks for the PR, but unfortunately, simply adding `5` to the mobile whitelist seems wrong. As suggested in my comment, I think the logic should be to explicitly match tablet when the UA contains `pad` and default to `mobile` in all other cases. Xiaomi has a lot of smartphone, and maintaining a whitelist is an issue. For instance, your patch will make the `MI 5` correctly typed, but not the `MI 6`. Here are all Xiaomi MI smartphones: https://xiaomi-mi.com/mi-smartphones/

**Comment by avdeev** [comment]
@loris Yes, you right
Be free to create other PR for other cases :)
Or you can create PR included my changes

**Comment by loris** [comment]
@avdeev Done! https://github.com/faisalman/ua-parser-js/pull/286
