### ISSUE TITLE
why is wrong and not friendly with MAC?

### ISSUE THREAD

**Issue by henryatman** [faisalman/ua-parser-js#283]
user_agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

get device: {vendor: undefined, model: undefined, type: undefined}

this "user_agent" info exactly show device is Macintosh, vendor is Apple, and is exactly Intel Mac OS X 10_13_1 computer,

why not correctly get it?

**Comment by alicoding** [comment]
I'm getting same issue here...

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36"
```

**Comment by ChamNouki** [comment]
according to getDevice() documentation, device seems not to be filled for desktop device.

**Comment by faisalman** [comment]
This has been discussed in #182
