### ISSUE TITLE
UC browser getting detected as Mobile Safari

### ISSUE THREAD

**Issue by ashrithkulai** [faisalman/ua-parser-js#294]
How to reproduce: 

Go to 
https://npm.runkit.com/npm
and run the code below 

var npm = require("npm")
var parse = require('user-agent-parser');
parse('Mozilla/5.0 (Linux; U; Android 4.2.2; en-US; Micromax A102 Build/MicromaxA102) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.1.0.882 U3/0.8.0 Mobile Safari/534.30')

**Comment by faisalman** [comment]
That library seems to have been deprecated, see https://www.npmjs.com/package/user-agent-parser
