### ISSUE TITLE
Enum for possible values of browser.name, os.name, device.type and device.vendor

### ISSUE THREAD

**Issue by yash-bagadia-zz** [faisalman/ua-parser-js#300]
Please export enum for all these so that consumers of the library don't have to hard-code strings in their code and maintaining the code is much easier.

**Comment by aaronpeterson** [comment]
My advice is to go straight to the horse's mouth and pluck them from test assertions.  I can't imagine a more right way to do it.

For example, all possible Browsers:

```javascript
const uaParserBrowsers = require('ua-parser-js/test/browser-test.json');

console.log(Object.keys(uaParserBrowsers.reduce((acc, e) => {
    acc[e.expect.name] = true;
    return acc;
}, {})).join(','))
````

Not sure about the space after Avant browser...

**Comment by karfau** [comment]
I can only second that. I'm actually basing some tests on the `browser-test.json` to be sure I'm notified if something breaks.

**Comment by fredrikssongustav** [comment]
@faisalman Is there any reason this is not already done or is this task up for grabs?

**Comment by faisalman** [comment]
```js
import { UAParser } from 'ua-parser-js';
import { Browser } from 'ua-parser-js/enums';

const userAgent = 'lynx/1.0';
const { browser } = UAParser(userAgent);
if(browser.is(Browser.LYNX) || browser.is(Browser.W3M)) {
  console.log('Serve a terminal-based page');
}
```
