### ISSUE TITLE
Feature: Default Viewport Sizes for mobile devices.

### ISSUE THREAD

**Issue by tracker1** [faisalman/ua-parser-js#301]
What would be a pretty nice feature, would be the portrait screen sizes for mobile devices.  This may be best as another module that could be used with this one.  It's just an idea.  I only suggest it because I often do server rendering different detecting mobile, and using the smallest preset (320px) in the render logic for any device matching `/(mobile|phone)/i`.  Shared rendering client-side and server-side (react) but would be very cool to get a little closer still to having a correct pre-render.

**Comment by faisalman** [comment]
This may suit for another library since we rarely found viewport size stated in user agent string..
