### ISSUE TITLE
Microsoft Loomia 950XL returns device undefined

### ISSUE THREAD

**Issue by ramonavic** [faisalman/ua-parser-js#302]
**User agent**
Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 950 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.15254

On Edge it said the browser was Chrome. 
On getDevice(): model vendor and type were undefined.

**Comment by ChamNouki** [comment]
seems to work well in preview : http://faisalman.github.io/ua-parser-js/

**Comment by faisalman** [comment]
Yup
