### ISSUE TITLE
License isn't quite MIT

### ISSUE THREAD

**Issue by tstibbs** [faisalman/ua-parser-js#317]
The license block in readme.md seems to be missing part of the MIT licence. As shown on https://opensource.org/licenses/MIT there is a warranty section that is missing from the readme.md.

The warranty clause is important and may mean that there are situations where it's acceptable to use MIT-licenced modules, but it isn't acceptable to use your module because it lacks the warranty section.

**Comment by tracker1** [comment]
Also calling out gplv2 isn't necessary, MIT can already be used in GPL software
