### ISSUE TITLE
Report OS kernel name and version seperately if possible

### ISSUE THREAD

**Issue by alexander255** [faisalman/ua-parser-js#319]
Hi! I like your library, but for my specific use-case I'd need the kernel name & version (if available) additionally to the OS name & version.

For instance for the string
`Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko`
the  `.getOS()` should return
`{name: "Windows", version: "7", kernel_name: "Windows NT", kernel_version: "6.1"}`.

Similarily the string
`Mozilla/5.0 (Linux; Android 6.0.1; Z832 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36`
should return
`{name: "Android", version: "6.0.1", kernel_name: "Linux", kernel_version: undefined}`.

I guess returning `XNU` for Apple OSes would also be fine but it's not part of the UA-String, so maybe not.

Is it OK if I open a PR about this?

**Comment by alexander255** [comment]
WTF, worum geht's?

**Comment by faisalman** [comment]
Maybe later
