### ISSUE TITLE
Android Browser reported as Mobile Safari

### ISSUE THREAD

**Issue by jayarjo** [faisalman/ua-parser-js#33]
Obviously this is because the UA string for Android browser is super weird. 

`Mozilla/5.0 (Linux; U; Android 4.0.2; en-us; Galaxy Nexus Build/ICL53F) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

Notice it claiming itself `AppleWebKit` and `Mobile Safari`...

But the script should still handle it somehow, like take into account platform part `Linux; U; Android 4.0.2`.

**Comment by faisalman** [comment]
It seems that `Version/x.x` part only showed up in Android Browser so I guess we can depend on this, unless..
