### ISSUE TITLE
This project don't work on android edge?

### ISSUE THREAD

**Issue by oldmtn** [faisalman/ua-parser-js#336]
Tested UA on android edge:
mozilla/5.0 (linux: android 6.0.1; nexus 5 build/mob30y) appelewebkit/537.36 (khtml, like gecko) chrome/67.03396.123 mobile safari/537.36 edga/42.0.0.233

Could you help to fix this issue?

**Comment by faisalman** [comment]
Fixed in #334

**Comment by oldmtn** [comment]
Thanks
