### ISSUE TITLE
Pixel C is being reported as a Pixel

### ISSUE THREAD

**Issue by matthew-english** [faisalman/ua-parser-js#347]
ua: Mozilla/5.0 (Linux; Android 8.0.0; Pixel C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.64 Safari/537.36

**Comment by masahills** [comment]
It is actually an issue with Chrome 70. It's not just a Pixel C but other models are affected as well.

Remove OS build number from user-agent string
https://www.chromestatus.com/feature/4558585463832576
