### ISSUE TITLE
Can add VLC to detection (maybe as browser)?

### ISSUE THREAD

**Issue by voxsoftware** [faisalman/ua-parser-js#348]
For example one user agent from VLC:
VLC/2.0.7 LibVLC/2.0.7

Can please add this like browser= VLC version=2.0.7

**Comment by faisalman** [comment]
You can detect VLC by uncommenting line 471:

https://github.com/faisalman/ua-parser-js/blob/7aca357879ba18ec2e57d36403d391c860a1be2e/src/ua-parser.js#L471

**Comment by voxsoftware** [comment]
Can say me what is the reason for commenting all lines of players?

**Comment by faisalman** [comment]
I'm still considering the best way to achieve this: https://github.com/faisalman/ua-parser-js/issues/227#issuecomment-310476422

**Comment by faisalman** [comment]
```js
import { UAParser } from 'ua-parser-js';
import { MediaPlayers } from 'ua-parser-js/extensions';

const userAgent = 'VLC/2.0.7 LibVLC/2.0.7';
const { browser } = UAParser(userAgent, MediaPlayers);
console.log(browser.name); // VLC
```
