### ISSUE TITLE
HUAWEI MediaPad M3 Lite 10 not recognized as Tablet

### ISSUE THREAD

**Issue by TkDodo** [faisalman/ua-parser-js#351]
I have a `HUAWEI MediaPad M3 Lite 10` Tablet, which sends the following userAgent string:

`Mozilla/5.0 (Linux; Android 7.0; BAH-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Safari/537.36`

It is, unfortunately, recognised as a Desktop. You can reproduce this on your own site (http://faisalman.github.io/ua-parser-js/):

<img width="882" alt="screenshot 2018-11-25 at 20 23 13" src="https://user-images.githubusercontent.com/1021430/48983495-fef32e00-f0ef-11e8-943a-62a6c5632321.png">

**Comment by lpappone** [comment]
Same issue with the following two tablets:
YOGA Tablet 2-1050F
UserAgent: `Mozilla/5.0 (Linux; Android 5.0.1; YOGA Tablet 2-1050F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.76 Safari/537.36`
Kindle Fire HDX 8.9:
UserAgent: `Mozilla/5.0 (Linux; Android 4.4.4; Kindle Fire HDX 8.9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Safari/537.36`

**Comment by condda** [comment]
We have a similar issue with a `HUAWEI MediaPad M5 lite`
UserAgent: `Mozilla/5.0 (Linux; Android 8.0.0; BAH2-W19 Build/HUAWEIBAH2-W19; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 Safari/537.36`

It is recognised as a mobile instead of a tablet.

**Comment by shawnbissell** [comment]
Seems like for the Kindle there is an easy way to detect them properly using the product-model in the ua string.
A list of the Fire devices can be found here:
https://docs.aws.amazon.com/silk/latest/developerguide/screen-size.html
