### ISSUE TITLE
Doesn't Update UserAgent data when device change without reload - testing with Google Device Toolbar

### ISSUE THREAD

**Issue by EduardoHidalgo** [faisalman/ua-parser-js#352]
I use Google Device Toolbar when i need to test a responsive web page, so this tool change UA data in the air, and doesn't reload the web page when i change device.

In this context (and thinking about using "ua-parser" as a way to detect when a page is resized/change device - as a way to detect device type in relation to its viewport size, without calculated this) i need a way to update UA data, without reload page.

**Comment by faisalman** [comment]
@EduardoHidalgo simply create a listener to [resize](https://developer.mozilla.org/en-US/docs/Web/Events/resize) event:

```js
window.addEventListener('resize', function(){
  console.log(UAParser());
});
```
