### ISSUE TITLE
device is not found

### ISSUE THREAD

**Issue by CrazySyntax** [faisalman/ua-parser-js#355]
Hi, 

This is the string I get for req.headers['user-agent']: 

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

When I run the following code: 

```
const parser = require('ua-parser-js');
const ua = req.headers['user-agent'];
const uaObj = parser(ua);
```

Then for uaObj.device I get: 
`{vendor: undefined, model: undefined, type: undefined}`

**Comment by slpn1** [comment]
Same issue

**Comment by bhanuprakashreddy7** [comment]
facing the same issue

**Comment by cravatcat** [comment]
same issue

**Comment by NHuebner1983** [comment]
Any updates on this? Assuming you can actually get the device information from a string that usually only exposes the operating system, version, browser+version...

**Comment by lucasgdev** [comment]
Any update on this? All device keys are returning undefined till now.

**Comment by faisalman** [comment]
This has been discussed in #283
