### ISSUE TITLE
Blocked by uBlock (and possibly Adblock plus)

### ISSUE THREAD

**Issue by scelza** [faisalman/ua-parser-js#356]
I wanted to alert you (and other developers) that uBlock started blocking ua-parser over the last day or two. It appears that ua-parser is on the [Adblock Plus EasyPrivacy list](https://easylist.to/easylist/easyprivacy.txt).

The uBlock Origin extension on GitHub shows this file being loaded in their [assets.json file](https://github.com/gorhill/uBlock/blob/master/assets/assets.json).

One workaround is to rename the file to parse-ua.min.js, as the list is only looking for ua-parser.*

It may be possible to submit a request to have this removed from the list, but I'm not sure.

**Comment by elbojoloco** [comment]
This isn't relevant when compiling into a single bundle right? (e.g. app.js)

**Comment by faisalman** [comment]
Fixed https://github.com/easylist/easylist/commit/8284cb40a4d2ed47810a398edcbb3da26f1608ae
