### ISSUE TITLE
Get Chromium version of Chromium-based browsers

### ISSUE THREAD

**Issue by Djaler** [faisalman/ua-parser-js#357]
For example, with given user agent:
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 YaBrowser/18.4.1.638 Yowser/2.5 Safari/537.36`.
Now I can use `getBrowser()` and receive `{ name: 'Yandex', version: '18.4.1.638' }`. But I also need to know about Chromium version (65.0.3325.181 in this case)

**Comment by JBYoshi** [comment]
This was merged in #390, but has not yet become part of a stable release yet.

**Comment by faisalman** [comment]
Fixed in #390
