### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by fantasy8-me** [faisalman/ua-parser-js#362]
Hi @faisalman from the discussion in #317 #266, understand you want to give more flexibility for people who need this software.
But because of this dual license(MIT, GPL v2),  some companies will simply treat it as copyleft lib, and don't allow the use of it.
As MIT license can be used in GPL software, and it is widely adopted by many js libs(e.g. React), can I suggest again that we simply keep the MIT one. Thanks

**Comment by frontendphil** [comment]
We're currently also auditing our dependencies and encountered exactly this issue.

**Comment by sandipp** [comment]
Any updates on this issue? We can expect new release with updated license?

**Comment by vuoya** [comment]
https://github.com/3rd-Eden/useragent <<<<< This one's MIT (though I haven't checked the dev dependencies (and obviously git isn't.... but of course it could be argued that distribution is completely independent of the distributation platform))

**Comment by faisalman** [comment]
Fixed in #380
