### ISSUE TITLE
iOS Instagram browser detected as: WebKit 

### ISSUE THREAD

**Issue by Canos** [faisalman/ua-parser-js#367]
The user agent string is: 
Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E302 Instagram 59.0.0.14.81 (iPhone7,2; iOS 11_3_1; es_ES; es-ES; scale=2.00; gamut=normal; 750x1334)

Not sure what browser name actualy is, instagram dont ask to choose a browser app instead. 
The parser gets "WebKit" as browser and as engine and 605.1.15 as version.

Tested in last version 0.7.19

**Comment by faisalman** [comment]
In-app browser on iOS usually uses WebKit
[https://developer.apple.com/documentation/webkit/wkwebview](https://developer.apple.com/documentation/webkit/wkwebview)

**Comment by yuvke** [comment]
> In-app browser on iOS usually uses WebKit
> https://developer.apple.com/documentation/webkit/wkwebview

@faisalman, isn't this true though also for the Facebook browser? It also uses Webkit under the hood, but there it seems you do parse the browser as "Facebook". Also note that Instagram add the string "Instagram" to the useragent so it seems that parsing the browser name as "Instagram" is doable.
