### ISSUE TITLE
UAParser does not parse correctly UserAgent String in NAVER APP WebView for iOS

### ISSUE THREAD

**Issue by sangyeonYoon** [faisalman/ua-parser-js#377]
## Version

ua-parser.min.js @version 0.7.1

## Development Environment

Browser  : NAVER app WebView
OS : iOS, iPhone

## Current Behavior
NAVER is search app, widely used in Korea
I think NAVER app modify useragent  and add 'NAVER (inapp; search; code; version; device)' to the end of UserAgent. this cause some trouble for parser.

I found sample UserAgent string from googling.(WRONG CASE, show below).
but it doesn't work now using recent UserAgent string from new version app and device in same environment

sorry for bad english.
```js
var userAgentString = 'Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_1_3 like Mac OS X; ko-kr) AppleWebKit/528.18 (KHTML, like Gecko) Mobile/7E18 NAVER(inapp; search; 103; 3.2.5)'

new UAParser(userAgentString).getOS()

//{name: "arch", version: undefined}

```

## Expected Behavior

{name: "iOS", version: 3.1.3}

**Comment by adopjay** [comment]
var regexes = {

        browser :
...

            /(NAVER)/i                                           // NAVER in app
            ], [NAME,'Naver'], [
            /(Whale)/i                                           // Whale Browser
            ], [NAME], [
            /(DaumApps)/i                                           // Daum in app
            ], [NAME, 'Daum'], [
            /(KAKAOTALK)/i                                           // Kakaotalk in app
            ], [NAME, 'KakaoTalk'], [

...

(Popular apps and browsers in Korea.)
Add this code in 'ua-parser.js'

추가한 다음에 minify 작업해서 사용하시면 될거같습니다.

**Comment by sangyeonYoon** [comment]
@adopjay 감사합니다 :)
