### ISSUE TITLE
Xiaomi not recognize 

### ISSUE THREAD

**Issue by OriAmir** [faisalman/ua-parser-js#382]
Hi, this is my user agent source : 
`
Rapnet/2.64.2 (Xiaomi Mi A1; U; Android 9; en-)
`
And the only thing I on the result is Android, without the device.

For example, if I try a Samsung user agent source :
`Rapnet/2.65.0.3 (Samsung SM-G950F; U; Android 9; en-)` 
In this case the results correct.

Whats can be wrong?
Tnx you very much.

**Comment by mllyx** [comment]
on Mi 9, Chrome's user agent is "Mozilla/5.0 (Linux; Android 9; MI 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
no "Build/PKQ1.181121.001" like other WebView base browser

**Comment by ekifox** [comment]
Mozilla/5.0 (Linux; Android 8.1.0; Redmi 5A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36

many of UAs like this are not responded by a parser, that's bad.

**Comment by ekifox** [comment]
Mozilla/5.0 (Linux; Android 8.1.0; Redmi 5A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36

many of UAs like that is not parsed, that's bad.

**Comment by faisalman** [comment]
Fixed in: https://github.com/faisalman/ua-parser-js/commit/e96f95802d1b61e4be391693cbe7d7743fc3e234
