### ISSUE TITLE
Edge and Firefox on iPad and Mac.

### ISSUE THREAD

**Issue by jenstroeger** [faisalman/ua-parser-js#384]
## Edge

The new [Edge Mobile](https://www.microsoft.com/en-us/windows/microsoft-edge-mobile) sends the following user agent string:
```
Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 EdgiOS/44.5.2 Mobile/15E148 Safari/605.1.15
```
which the `ua-parser-js` on [whatsmyua.info](https://www.whatsmyua.info/) (see also issue https://github.com/sandinmyjoints/whatsmyua/issues/9) matches as follows:

![ua](https://user-images.githubusercontent.com/12053937/61684615-58822a00-ad5d-11e9-88f2-cc5fe63b1e22.jpg)

I would have expected that “Edge” or “Edge Mobile” is the browser’s name. Similarly, the following using Edge on my Mac:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3829.0 Safari/537.36 Edg/77.0.197.1
```
results in the following object (using 0.7.20)

![edge](https://user-images.githubusercontent.com/12053937/61687697-67210f00-ad66-11e9-8b1e-91b78be53fde.jpg)

Here I’d have expected that the browser’s name is “Edge”?

## Firefox

Then, Firefox on iPad with this user agent string
```
Mozilla/5.0 (iPad; CPU OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/18.1b15719 Mobile/15E148 Safari/605.1.15
```
returns a “Safari” browser with undefined version (again, that’s with 0.7.11).

**Comment by faisalman** [comment]
These has been fixed in latest version 👍
