### ISSUE TITLE
Not support the Vietnamese CocCoc browser

### ISSUE THREAD

**Issue by vhsvuong86** [faisalman/ua-parser-js#388]
Hi, 
In VietNam, there're many people which currently using the CocCoc browser. It's also use the Chromium as the kernel, then add some feature for Vietnamese only

Please help to support us to detect the CocCoc browser 

Thanks a lot,
Vuong Vu

**Comment by faisalman** [comment]
Related: #368

**Comment by faisalman** [comment]
Fixed in #368
