### ISSUE TITLE
Browser: Mobile Safari vs WebKit

### ISSUE THREAD

**Issue by karfau** [faisalman/ua-parser-js#403]
For the following UA:
`Mozilla/5.0 (iPad; CPU OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

The lib reports `WebKit` as a browser and engine name, while the version of both is set to `605.1.15`.

From the list of browsers in the README and the tests in `browser-test.json` I would have expected a name of `Mobile Safari` and a version of 13 (so it can e.g. be related to a minimum iOs/Safari version of 11)

Is there a way to detect these as "Mobile Safari"?

Issues potentially related: #387 , #300

**Comment by faisalman** [comment]
Unless there is `Safari/[version]` token, we can't be certain whether it's `Mobile Safari` or just another in-app browser since they share similar user-agent string.
