### ISSUE TITLE
Support WhatsApp

### ISSUE THREAD

**Issue by joseph1125** [faisalman/ua-parser-js#412]
Recently I need to implement specific logic if WhatsApp bot is detected, is it possible to provide a way to detect WhatsApp?

The user agent of WhatsApp is WhatsApp/2.19.81 A

**Comment by faisalman** [comment]
Hi @joseph1125 you can detect any user agent which isn't currently exists in this library by making use of extension, simply pass your own regex(es) when instantiating a new UAParser object (see https://github.com/faisalman/ua-parser-js#extending-regex-patterns)

As an example: https://jsfiddle.net/bnhwfjsm/

```js
var myExtension = [[/(whatsapp)\/([\w\.]+)/i], [UAParser.BROWSER.NAME, UAParser.BROWSER.VERSION]];
var myParser = new UAParser({ browser: myExtension});
var uaString = 'WhatsApp/2.19.81 A';
console.log(myParser.setUA(uaString).getBrowser());   // {name: "WhatsApp", version: "2.19.81"}
```

**Comment by joseph1125** [comment]
Thanks, I already solve this issue by adding WhatsApp and Facebook in app browser

**Comment by faisalman** [comment]
No problem, I might as well adding WhatsApp in future release.. still considering for now
