### ISSUE TITLE
Motorola device model O

### ISSUE THREAD

**Issue by elandi-branch** [faisalman/ua-parser-js#413]
Using ua-parser-js (v0.7.20) I am getting unexpected results for model name. Below are a few examples (not a complete list) of user agents that result in Motorola device model O. Can you please verify why these user agents have this result and fix if this is determined to be a bug?

Ex 1 
User Agent: Mozilla/5.0 (Linux; Android 9; moto g(6) play) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36
Expected Device Model: moto g(6) play
Actual Device Model: o

Ex 2
User Agent: Mozilla/5.0 (Linux; Android 7.1.1; Moto E (4) Build/NDQS26.69-64-11-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36
Expected Device Model: Moto E (4)
Actual Device Model: O

Ex 3
User Agent: Mozilla/5.0 (Linux; Android 9; moto g(7) supra Build/PCOS29.114-134-2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36
Expected Device Model: moto g(7) supra
Actual Device Model: o

**Comment by jleebranch** [comment]
Ideally, we would want these to be classified in this manner:
moto g(6) -> 'Motorola Moto G'
moto g(7) -> 'Motorola Moto G'
Moto E (4) -> 'Motorola Moto E'
