### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by arthedza** [faisalman/ua-parser-js#415]
I checked up my node_modules and found that this module referenced deprecated UIWebView
https://developer.apple.com/documentation/uikit/uiwebview

**Comment by ashu090990** [comment]
My app got rejected because UIWebView, I need a Workground for now, can someone  help me.

**Comment by arthedza** [comment]
> My app got rejected because UIWebView, I need a Workground for now, can someone help me.

You can just check out for any UIWebView references and if you find nothing you can simply delete UIWebView file

**Comment by faisalman** [comment]
I'm not using UIWebView anywhere, that might come up because I have this line in a test file: https://github.com/faisalman/ua-parser-js/blob/ec5a864abb4b30c5143c3f870d73d807697cf610/test/browser-test.json#L1163

Seems to be related: https://github.com/facebook/fbjs/issues/362#issuecomment-627143283
