### ISSUE TITLE
Kindle is not detected as mobile device

### ISSUE THREAD

**Issue by nguyenngochoang** [faisalman/ua-parser-js#416]
I have an kindle device with this userAgent: Mozilla/5.0 (Linux; Android 5.1.1; KFAUWI) AppleWebKit/537.36 (KHTML, like Gecko) Silk/79.4.9 like Chrome/79.0.3945.136 Safari/537.36

And the library didnt work properly for this one. 
![image](https://user-images.githubusercontent.com/26711150/76183495-2b568f00-61fb-11ea-8212-e37e9c0eb90c.png)

**Comment by faisalman** [comment]
This was fixed in https://github.com/faisalman/ua-parser-js/commit/7b23335d290a9225dcb094652e15677ef3227852
