### ISSUE TITLE
Ubuntu Chromium parsed incorrectly

### ISSUE THREAD

**Issue by rwwagner90** [faisalman/ua-parser-js#418]
When using Chromium on Ubuntu `getOs` returns `Linux`, but if you use Firefox on Ubuntu, it correctly returns `Ubuntu`. Any thoughts on why Chromium is working differently?

**Comment by faisalman** [comment]
`Ubuntu` field was removed by Chromium team which I believe as an effort to prevent browser fingerprinting https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1877073
