### ISSUE TITLE
GetDevice  - Not recognizing new browsers

### ISSUE THREAD

**Issue by pgiani** [faisalman/ua-parser-js#419]
You can reproduce the issue by visiting the    [DEMO URL](http://faisalman.github.io/ua-parser-js/),
I have also included some user agent strings from the browsers I used

![Screen Shot 2020-03-23 at 2 10 04 PM](https://user-images.githubusercontent.com/5713173/77359196-d2b1e680-6d10-11ea-8370-f83f0fffc04e.png)

**Safari** Version: 13.0.5 
 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15`

**Google Chrome**  Version: 80.0.3987.149 (Official Build) (64-bit)
`Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.4; en; rv:1.9.0.19) Gecko/2011091218 Camino/2.0.9 (like Firefox/3.0.19)`

**FireFox**  Version: 75.0b7 (64-bit)
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0`

**Vivaldi**  Version: 2.11.1811.47 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.136 Safari/537.36 `

**Comment by faisalman** [comment]
What is the expected result for the device section in this issue? generally, if the device model wasn't found we can assume that it might just a typical PC (see #182)
