### ISSUE TITLE
unrecognize facebook app for ios

### ISSUE THREAD

**Issue by wxy1995** [faisalman/ua-parser-js#421]
My facebook app user-agent string:

Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,3;FBMD/iPhone;FBSN/iOS;FBSV/13.0;FBSS/3;FBID/phone;FBLC/zh_CN;FBOP/5;FBCR/中-国-联-通-]

`/;fbav\/([\w\.]+);/i` can not detect it.

**Comment by nionata** [comment]
I am experiencing a similar issue. It looks like the older iOS FB UA are being detected properly. 

Older iOS FB UA being detected as Facebook:
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 [FBAN/FBIOS;FBAV/96.0.0.45.70;FBBV/60548545;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3.2;FBSS/2;FBCR/o2-de;FBID/phone;FBLC/de_DE;FBOP/5;FBRV/0]`

Newer iOS FB UA being detected as WebKit:
`Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,2;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBCR/]`

It looks like Facebook changed part of the UA string `FBAN/FBIOS;FBAV` v `FBAN/FBIOS;FBDV`. I am going to see if adding this to the regex solves the issue.

**Comment by nionata** [comment]
From [facebook best practices](https://developers.facebook.com/docs/sharing/best-practices#crawl): "FB_IAB/FB4A for Android and FBAN/FBIOS for iOS"

**Comment by faisalman** [comment]
Since this issue has been fixed, I'm closing this 👍
