### ISSUE TITLE
@types/ua-parser-js: This expression is not callable

### ISSUE THREAD

**Issue by ochanje210** [faisalman/ua-parser-js#423]
When you follow the simple parsing example with typescript, you get the following error.

<img width="689" alt="Screen Shot 2020-05-06 at 9 27 38 PM" src="https://user-images.githubusercontent.com/16204807/81176674-706f2580-8fe0-11ea-9f8a-d7598f05d7d1.png">

**Comment by rvanlaarhoven** [comment]
Bumped into the same thing. I'm using the following instead for now;

```javascript
import { UAParser } from 'ua-parser-js'
const ua = new UAParser(req.headers['user-agent'])
```

**Comment by morscho** [comment]
> ```js
> import { UAParser } from 'ua-parser-js'
> const ua = new UAParser(req.headers['user-agent'])
> ```

Thank you for that suggestion.
We are using ua-parser-js in our protractor config and I was able to get to get rid of the initial error (_This expression is not callable_) with a modified version of your solution:
```
import { UAParser } from 'ua-parser-js'
[...]
// onPrepare()
const userAgent = new UAParser(await browser.driver.executeScript('return navigator.userAgent')).getResult();
```

**Comment by faisalman** [comment]
Any issue with `@types` might be more relevant here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25202#issuecomment-383393664

**Comment by ippeiukai** [comment]
UAParser signature is now callable in [`@types/ua-parser-js@0.7.36`](https://www.npmjs.com/package/@types/ua-parser-js).

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52901
