### ISSUE TITLE
Unable to get some device details.

### ISSUE THREAD

**Issue by mantupani17** [faisalman/ua-parser-js#431]
i am not getting some device details In my project ,any solution like VIVO or RealMe mobile devices.

**Comment by faisalman** [comment]
Hi please open a new issue which also includes user agent of those devices, thanks 👍

**Comment by shubham22716** [comment]
Mozilla/5.0 (Linux; Android 11; RMX2117) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36

Mobile Brand is Realme
