### ISSUE TITLE
Samsung Galaxy Tab S6 Lite is detected as a phone

### ISSUE THREAD

**Issue by derUli** [faisalman/ua-parser-js#435]
The Samsung Galaxy Tab S6 Lite (SM-P610) is detected as a phone. But it is a tablet.

Example UA String:
Mozilla/5.0 (Linux; Android 10; SAMSUNG SM-P610) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.0 Chrome/79.0.3945.136 Safari/537.36

**Comment by derUli** [comment]
I added a pull request for this device
https://github.com/faisalman/ua-parser-js/pull/436

**Comment by faisalman** [comment]
Merged. Thanks 👍
