### ISSUE TITLE
Android devices not recognized any more

### ISSUE THREAD

**Issue by tjw02** [faisalman/ua-parser-js#438]
The following Android useragent isn't returning the correct information:

Mozilla/5.0 (Linux; Android 7.1.2; TC75x) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36

**Comment by faisalman** [comment]
Hi @tjw02 what is the expected device result? as for now I believe we identify the model part as TC75x correctly, the only missing result here is the vendor part. A quick google indicate it as Zebra's: https://www.zebra.com/us/en/support-downloads/mobile-computers.html
