### ISSUE TITLE
Please add support for ES2015 

### ISSUE THREAD

**Issue by iztokb** [faisalman/ua-parser-js#441]
Looks like that current version is available as CommonJS module only.

Angular build warn about this when building app. More here: https://web.dev/commonjs-larger-bundles/

Is it possible to release package as ES2015 module as well?

Br

**Comment by siir** [comment]
I second this request.

**Comment by alfaproject** [comment]
I guess there's no hope for this. Is there any other modern package that can do the same thing?

**Comment by mxdvl** [comment]
We had a specific use case where we needed this to work, and it’s possible to [turn this into an ES Module by stripping away a few things](https://raw.githubusercontent.com/guardian/csnx/ddfb37704a82df524ac2407d77544f73f3d38c6a/apps/ua-parsing/src/ua-parser.js).
