### ISSUE TITLE
Just a request...

### ISSUE THREAD

**Issue by rayj00** [faisalman/ua-parser-js#442]
I am fairly new to javascript.  I am in need of determining if my site will be accessed by mobile, tablet, desktop, etc and came across ua-parser-js.   I believe it will do what I want, however, being new, I am not sure how to use it.

If I access ua-parser-js from my server,  how do I code a parse for the device type for instance? I want to know if it is mobile so I can then adjust video size.

If there is a forum where I can ask questions about this, please let me know.

Thanks,

Ray

**Comment by asaharan** [comment]
Here is the example for node.js
https://www.npmjs.com/package/ua-parser-js#using-nodejs

To get device type you can use
```
var parser = require('ua-parser-js');
var ua = parser(req.headers['user-agent']);
var deviceType = ua.getDevice().type // this is what you needed
```

You can ask questions on [stackoverflow.com](https://stackoverflow.com), this is really not the right place for them.

**Comment by faisalman** [comment]
Agreed, stackoverflow will be more helpful for this kind of question
