### ISSUE TITLE
Google Cloud Firebase Nodejs Implementation

### ISSUE THREAD

**Issue by digitaico** [faisalman/ua-parser-js#443]
Hi this is a terrific packet.  Thanks,
I can't make it work on nodejs in GCP Cloud Firebase functions.
I've read your documentation,  also at npm,  but again,  can make it work.
The object is not correctly instantiated, so error messages return that a given method is not a function of...
So where I can find more documentation.  thanks

**Comment by faisalman** [comment]
I'm not really sure, could be something wrong in your configuration
