### ISSUE TITLE
Opera on Windows/Mac OS

### ISSUE THREAD

**Issue by fivedogit** [faisalman/ua-parser-js#46]
Hi. Thanks for writing ua-parser-js. It's perfect for my needs.

I'm having trouble with Opera on Mac OS, though. 

if(result.browser.name === "Opera" && (result.os.name === "Windows" || result.os.name === "Mac OS"))
{
    // returns true for windows
}
else
{
   // returns false for macOS
}

I'm using a user agent switcher and here is my user agent string in Mac:

Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.9.168 Version/11.52

Windows:

Opera/9.80 (Windows NT 6.1; WOW64; U; en) Presto/2.10.229 Version/11.62

I don't have a real mac to test on, unfortunately. Any ideas as to what could be going wrong?
- fivedogit

**Comment by faisalman** [comment]
Please try again in http://faisalman.github.io/ua-parser-js/ as both string were recognized perfectly

`Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.9.168 Version/11.52` was identified as Opera in Mac

`Opera/9.80 (Windows NT 6.1; WOW64; U; en) Presto/2.10.229 Version/11.62` was identified as Opera in Windows
