### ISSUE TITLE
Firefox 3.6 UA incorrectly parsed 

### ISSUE THREAD

**Issue by vinyldarkscratch** [faisalman/ua-parser-js#461]
Given the UA: `Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US; rv:1.9.2.17) Gecko/20110420 Firefox/3.6.17 (.NET CLR 3.5.21022)`

Expected:
```
name: Firefox
version: 3.6
major: 3
```

Actual:
```
name: Mozilla
version: 5.0
major: 5
```

Diagnosis: it looks like the `(.NET CLR 3.5.21022)` at the end is messing with the detection.  Removing it gives the correct results.

**Comment by faisalman** [comment]
I'm closing this issue as it will be fixed in #464 just waiting for small changes from @vinyldarkscratch
