### ISSUE TITLE
package-lock.json not created; why?

### ISSUE THREAD

**Issue by vinyldarkscratch** [faisalman/ua-parser-js#462]
I noticed that in #334, a `.npmrc` file was added to prevent creating a `package-lock.json` file.  I'm curious: why omit this file?  There's a number of reasons to not only create it, but commit it into the repository (some described in https://stackoverflow.com/a/44210813/2608838).

**Comment by faisalman** [comment]
Maybe because I still have no sense of urgency whether to create or prevent, since this package only use limited dependencies ..well.. at least until something breaks (let's hope not 😁)
