### ISSUE TITLE
Assertion doesn't stop for every tab

### ISSUE THREAD

**Issue by korayt** [faisalman/ua-parser-js#468]
Hey I'm fairly new to frontend programming and recently I was assigned to a chrome extension project that uses this library. It's a great library but when I try to create an assertion and select an element to make an assertion check, assertion screen still want me to click to an element to assert in different tabs although I selected an element on my active chrome tab.

**Comment by faisalman** [comment]
Hi, sorry I didn't get the exact problem you're currently facing. In general, if the problem is not within the scope of library itself, it's better to ask in forum like stackoverflow etc.
