### ISSUE TITLE
Parser Error 

### ISSUE THREAD

**Issue by davidedeluca02** [faisalman/ua-parser-js#475]
Parser error for this two devices

Mozilla/5.0 (Linux; Android 9; moto g(6) plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10; Nokia 3.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36

Motorola G6 Plus --> parser output "o"
Nokia 3.2 --> parser output "3"

**Comment by faisalman** [comment]
Motorola "O" issue was already fixed in #413
