### ISSUE TITLE
Edge recognized as Chrome in $.ua object

### ISSUE THREAD

**Issue by kloh-fr** [faisalman/ua-parser-js#480]
I'm playing a bit with UAParser right now and met an unexpected result using `$.ua` object.
With latest Edge version, the browser displayed is Chrome!

My ua string is this one:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.63
```
With standard method `parser.getBrowser().name` and `parser.getBrowser().version` I get:
```
Edge
88.0.705.63
```

With jQuery object `$.ua.browser.name` and `$.ua.browser.version` I get:
```
Chrome
88.0.4324.150
```

Tested because jQuery is used on the site but I'll go with the classic way so. :-p

**Comment by faisalman** [comment]
Hi @kloh-fr thanks for reporting this, however I'm having trouble to reproduce that kind of behavior using latest Edge (89.0.774.54): https://jsfiddle.net/6djhayw4/

**Comment by faisalman** [comment]
Currently I can't be sure what might be the cause of this issue, please re-open if you still experiencing the problem along with steps to reproduce or maybe something that I can confirm.. thanks 👍

**Comment by kloh-fr** [comment]
Sorry didn't get much time this week. I'll let you know more precisely if I reproduce it. Thank you.
