### ISSUE TITLE
Ipad Air not recognized

### ISSUE THREAD

**Issue by jf-niji** [faisalman/ua-parser-js#481]
Hello,

'device' object is not recognized on my device.

Device : Ipad Air 3
iOS version : 14.3
User agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

ua-parser object : ```{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
  "browser": {
    "name": "Safari",
    "version": "14.0.2",
    "major": "14"
  },
  "engine": {
    "name": "WebKit",
    "version": "605.1.15"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.6"
  },
  "device": {},
  "cpu": {}
}```

Device should be : ```{"vendor":"Apple","model":"iPad","type":"tablet"}```

**Comment by faisalman** [comment]
Duplicate #417
