### ISSUE TITLE
In some Motorolas the device model is 'o'

### ISSUE THREAD

**Issue by alexisllamas** [faisalman/ua-parser-js#485]
Looks like in some Motorolas, like the Moto e5, the device model is 'o'.

This is the user agent: `Mozilla/5.0 (Linux; Android 8.0.0; moto e5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Mobile Safari/537.36`

![Screen Shot 2021-03-23 at 12 16 43](https://user-images.githubusercontent.com/11366687/112197373-a229b480-8bd1-11eb-8d9d-6a331ca85824.png)

Let me know if it can be fixed and if I can help you with something

![Screen Shot 2021-03-23 at 12 17 57](https://user-images.githubusercontent.com/11366687/112197530-ce453580-8bd1-11eb-9cb2-ee8c2263a155.png)

**Comment by faisalman** [comment]
Hi yes it's a bug (see #413) and has been fixed recently in https://github.com/faisalman/ua-parser-js/commit/d78a2e0361cc0ce4574f1abb824c14fce1f5f830 just hasn't been published yet. Meanwhile the demo page is still using the latest published version [0.7.24](https://github.com/faisalman/ua-parser-js/releases/tag/0.7.24)
