### ISSUE TITLE
Lenovo tablets are identified as phones

### ISSUE THREAD

**Issue by stofolus** [faisalman/ua-parser-js#486]
Hi!

It seems like some Lenovo tablets are mistakenly identified as phones. Here is an example UA

`Mozilla/5.0 (Linux; Android 9; Lenovo TB-X705F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36`

I think they've changed from `Lenovo Tab` into `Lenovo TB-` on some of their tablets. I don't have any more tablets to verify that on though.

**Comment by faisalman** [comment]
Hi yes it's confirmed (see #449) and has been fixed recently in https://github.com/faisalman/ua-parser-js/commit/1a8cd671abfc7a63aadb69496b7c0405259f49ab just hasn't been published yet. Meanwhile the demo page is still using the old version `0.7.23`.
