### ISSUE TITLE
Can't detect Apple's new M1 Chip with arm architecture.

### ISSUE THREAD

**Issue by rommelmamedov** [faisalman/ua-parser-js#489]

**Comment by felixakiragreen** [comment]
Can confirm, on my M1 MacBook Air I get:
```
device: {vendor: undefined, model: undefined, type: undefined}
```

**Comment by p3yman** [comment]
Confirm, I have this result too

**Comment by wscourge** [comment]
+1

ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0"

<img width="198" alt="image" src="https://user-images.githubusercontent.com/16985871/159626667-a9b2af8d-cd79-466a-a6f6-4d44d32297af.png">

**Comment by PrimeDominus** [comment]
Any solution for this?

**Comment by seanaye** [comment]
I'm acutally using this as a feature not a bug. If the os is MacOS but the CPU is undefined then I can tell it is an apple silicon device.

**Comment by rommelmamedov** [comment]
> I'm acutally using this as a feature not a bug. If the os is MacOS but the CPU is undefined then I can tell it is an apple silicon device.

Yeah, but there are already 5-6 different silicon CPUs (M1, M1 Pro, M1 Max, M1 Ultra, M2) who will you identify them?

**Comment by steven-tey** [comment]
having this issue as well 😕 

an alternative I'm trying out is https://github.com/etienne-martin/device-detector-js – it detects M1 Macs correctly

**Comment by faisalman** [comment]
Can anyone with Apple Silicon device confirm this is correct? using `navigator.userAgentData`

https://stackoverflow.com/questions/65146751/detecting-apple-silicon-mac-in-javascript#answer-75177111

**Comment by wscourge** [comment]
```
await navigator.userAgentData.getHighEntropyValues(['architecture'])
```

Firefox:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/16985871/226861388-feb056a9-ba85-43a2-85c7-620504cc2579.png">

Chrome:
![image](https://user-images.githubusercontent.com/16985871/226861624-3a32de15-45a7-4246-a22a-a3bbeee310fd.png)

Safari:
![image](https://user-images.githubusercontent.com/16985871/226861803-a65de613-1882-444b-8e37-3dba50c00f1e.png)
