### ISSUE TITLE
ua-parser-js doesn't extract case of WebOS

### ISSUE THREAD

**Issue by taihoon** [faisalman/ua-parser-js#492]
ua-parser-js doesn't extract case of WebOS
![image](https://user-images.githubusercontent.com/13197080/113661812-c57c5580-96e1-11eb-8f11-ef3a3f1e82ef.png)

here is WebOS useragent string:
https://webostv.developer.lge.com/discover/specifications/web-engine/

**Comment by faisalman** [comment]
The current code as it is now should be able to capture `WebOS`  just fine, but strangely fails.. after a closer look, it turns out that the official string is `Web*zero*S` instead of `Web*O*S` :roll_eyes:

**Comment by taihoon** [comment]
`Web*zero*S ` is real useragent string for webos! 👎

**Comment by faisalman** [comment]
I know, wonder why :thinking:
