### ISSUE TITLE
Brave mobile browser not being detected as device.type = mobile

### ISSUE THREAD

**Issue by Verdoso** [faisalman/ua-parser-js#493]
Hi there,
I'm using UAParser to detect if the user is accesing a page from a mobile or desktop to display the phone numbers as links or not and I'm having some issues with the Brave browser.

Chrome works fine using the same phone, but Brave specifies the user-agent "Mozilla/5.0 (Linux; Android 11; Mi A3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Mobile Safari/537.36" and even though it reads Android and Mobile, the device type returned by UAParser is not 'mobile'.

Are those criteria not enough to satisfy the 'mobile' criteria?

I had a look at the code but I'm not familiar enought with it to see where the issue might be. 

Is that a Brave issue?

Thanks

**Comment by faisalman** [comment]
Hi @Verdoso thanks for reporting. I think there shouldn't be an issue, could you try visit the demo page: https://faisalman.github.io/ua-parser-js/ and share the result?

**Comment by Verdoso** [comment]
Hi,
The page detects it correctly as mobile, so it most probably is an issue on my side. I just make a thin wrapper on Vue and instantiate a default UAParser instance, then use the result device type to display a block or not.
I'll check versions and try to get more debug info from the device on monday.

Thanks for your help.

**Comment by Verdoso** [comment]
Ok, it seems it was some kind of weird caching issue in the middle tier.
I apologise for the confusion and thanks for the help. Thanks for the library also ;).

Cheers
