### ISSUE TITLE
Handle Email Proxies

### ISSUE THREAD

**Issue by kdallmeyer-sr** [faisalman/ua-parser-js#494]
Gmail and Yahoo proxy images and use a special User-Agent String. This library is unable to parse them properly. There might be other email proxies.

Gmail: [`Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)`
](https://www.scientiamobile.com/what-is-google-image-proxy/)

Yahoo Mail: `YahooMailProxy;%20https://help.yahoo.com/kb/yahoo-mail-proxy-SLN28749.html`

**Comment by faisalman** [comment]
In the meantime there is no support for email proxies, but you can add it now using extension: https://github.com/faisalman/ua-parser-js#extending-regex

```js
const result = UAParser("Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)", 
{ 
  browser : [[/(googleimageproxy|yahoomailproxy)/i], [UAParser.BROWSER.NAME]]
});

console.log(result.browser); // { name: "GoogleImageProxy", version: undefined, major: undefined }
```
