### ISSUE TITLE
Does not work with the latest brave browser

### ISSUE THREAD

**Issue by chaitanyapotti** [faisalman/ua-parser-js#498]
Here's the result from brave browser

![image](https://user-images.githubusercontent.com/1688380/120422460-e5a35a80-c39a-11eb-960a-9a8746e2e173.png)

**Comment by edwinbbu** [comment]
getBrowser() return `Chrome` instead of `Brave`

**Comment by PlussRolf** [comment]
Same here, tested on standalone lastest versión and online.

![image](https://user-images.githubusercontent.com/7097088/128760289-c3b74222-71fc-4c6b-bbc5-ae8b0c3eb58a.png)
![image](https://user-images.githubusercontent.com/7097088/128760316-1f094d17-e44f-4237-9be5-793035b9f2fd.png)

**Comment by stefanboz** [comment]
Still not working as of March 10th 2022

![image](https://user-images.githubusercontent.com/29125505/157640812-16c52c74-9399-4363-a0d2-3546b350a02b.png)

**Comment by faisalman** [comment]
This is the intended behavior for Brave, quoting from https://github.com/brave/brave-browser/issues/1052#issuecomment-420075841, they ultimately decided to remove specific Brave user-agent string

> As a general policy, we don't want the `user-agent` string to make Brave users much more distinctive. Our general ballpark plan is to switch to a Brave UA when users on that platform will have an anonymity set of about a million.
