### ISSUE TITLE
Samsung Devices have dropped brand identification from UserAgent string

### ISSUE THREAD

**Issue by sallyhill** [faisalman/ua-parser-js#499]
At some arbitrary point, it seems like Samsung dropped the "SM" from their User Agent string.

When I run `navigator.userAgent` in the console, casting from my Samsung Galaxy s10 device, it returns: `"Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Mobile Safari/537.36"`

As a result, my samsung device is not being detected from the ua-parser-js library.
![image](https://user-images.githubusercontent.com/12820071/121516708-64078a00-c9a3-11eb-8f49-0acd3158ebd3.png)

**Comment by faisalman** [comment]
It is the intended behavior since Chrome starts hiding model name of the device in favor of user agent client hints. You can track the related issue here: https://github.com/faisalman/ua-parser-js/issues/408

https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/
