### ISSUE TITLE
`getBrowser().name` returns `''` when Internet Explorer for Windows Phone 8.1 Update

### ISSUE THREAD

**Issue by min9nim** [faisalman/ua-parser-js#501]
`getBrowser().name` returns `''` when Internet Explorer for Windows Phone 8.1 Update

```js
const uaParser = new UAParser('Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537')

uaParser.getBrowser().name // returns ''
```

userAgent string,

`Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537`

is from 
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/hh869301(v=vs.85)?redirectedfrom=MSDN

It should be returned `IE`

**Comment by faisalman** [comment]
It's currently detected as `IEMobile` as can be seen here: https://faisalman.github.io/ua-parser-js/
