### ISSUE TITLE
Custom  version mapping, namely for windows?

### ISSUE THREAD

**Issue by LeeGDavis** [faisalman/ua-parser-js#504]
Is there a way to have a custom version map for windows or any os for that matter?  I'm really only concerned with the actual Major and Minor versions reported in the ua string (without the 'NT'), like 6.2, 6.3, 10.0.  

Thanks!

**Comment by faisalman** [comment]
You can use extension feature: https://github.com/faisalman/ua-parser-js#using-extension

```js
UAParser({ 

    os: [

        [/(windows)[\/ ]?[ntce]+([\d\. ]+\w)(?!.+xbox)/i], 
        [UAParser.OS.NAME, UAParser.OS.VERSION],

        [(win(?=3|9|n)|win 9x )nt([\d\.]+)], 
        ['Windows', UAParser.OS.VERSION]

    ]; 
});
```
