### ISSUE TITLE
DuckDuckGo mobile browser detected as desktop device

### ISSUE THREAD

**Issue by josebrito** [faisalman/ua-parser-js#513]
The following DuckDuckGo browser user agent is detected as a desktop device:

```
Mozilla/5.0 (Linux; Android 8.1.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile DuckDuckGo/5 Safari/537.36
```

**To reproduce:**

Place the above user agent in the ua-parser demo app: https://faisalman.github.io/ua-parser-js/

**Comment by jnagle-nf** [comment]
This issue is affecting us as we're using [duskload/react-device-detect](https://github.com/duskload/react-device-detect) as a dependency. Can you please fix this?
