### ISSUE TITLE
xterm.js

### ISSUE THREAD

**Issue by 33Crypto** [faisalman/ua-parser-js#514]
#Create
{o-code-o}{o-LOCK33SystemParserDirectory-o}{O-NODE-O}</File-Edit>{-o-}(repository)
#Add_Update(ua-parser-js)
#Review_Commit

**Comment by faisalman** [comment]
GoogleApp/1.1.1.1.arm
GoogleApp/1.1.1.1"a
GoogleApp/1.1.1.1/'a
GoogleApp/1.1.1.1/"a
GoogleApp/1.1.1.1/a'a
GoogleApp/1.1.1.1/a"a
