### ISSUE TITLE
iOS devices not read with detail model information

### ISSUE THREAD

**Issue by qingzhuozhen** [faisalman/ua-parser-js#520]
It seems for apple devices, the library is not reading detail model information but just general iphone, ipad, etc. For example, for user agent `Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone12,5;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/3;FBID/phone;FBLC/en_US;FBOP/5;FBCR/]` the library is reading device model as iPhone, but not iPhone12,5, which could tell this is from iPhone 11 Pro Max. Ideally we should have mode detail model information in devices if possible.

**Comment by qingzhuozhen** [comment]
Just created an PR https://github.com/faisalman/ua-parser-js/pull/521 to fix this issue

**Comment by faisalman** [comment]
Fixed in https://github.com/faisalman/ua-parser-js/commit/a1d816ae21e18c8debbe5f23657a0ce750290317
