### ISSUE TITLE
Year/Date of browser release

### ISSUE THREAD

**Issue by intellix** [faisalman/ua-parser-js#530]
We're using User Agent parsing in NodeJS to guess the size of the screen before delivering the website. 

Currently you can get a few bits of information from UAParser like: Browser and Version but we don't know when that browser/version combination were released and how old it is.

It would be nice if we could get the date or year of when the browser being used was released so we can get a general idea of how up-to-date their browser/computer is.

**Comment by faisalman** [comment]
With dozens of browser releases every year, I guess this kind of feature is something that I can't probably keep up with
