### ISSUE TITLE
Security issue: compromised npm packages of ua-parser-js (0.7.29, 0.8.0, 1.0.0) - Questions about deprecated npm package ua-parser-js

### ISSUE THREAD

**Issue by SuperOleg39** [faisalman/ua-parser-js#536]
Hi!

See a warning at npm - https://www.npmjs.com/package/ua-parser-js - `This package has been hijacked. Please revert to 0.7.28`

First question - Can we use range `^0.7.28`, or it is not safe?

Second question - Will you create a new package, or try to remove hijacked versions and continue update this package?

**Comment by RandomYser** [comment]
Is there a way to know all packages dependent on these specific versions? There are 1200 odd dependents marked in npm but that's for all versions, I think.

**Comment by nypinstripes** [comment]
@faisalman without reading through all the 400 comments here, can you tell us is v1.0.2 safe to use?

**Comment by ccravens** [comment]
Hello all, I've created a petition to get NPM's attention to prevent this from happening, please sign and share this petition to show NPM we demand better security procedures on released packages!

https://www.change.org/p/npm-please-secure-package-releasing

**Comment by alex-drocks** [comment]
> > Hello all, I've created a petition to get NPM's attention to prevent this from happening, please sign and share this petition to show NPM we demand better security procedures on released packages!
> > https://www.change.org/p/npm-please-secure-package-releasing
> 
> 2-factor authentication is already there. Probably @faisalman didn't have that set up before the incident. I don't see the need for a petition.

Signed

**Comment by alex-drocks** [comment]
> Hello all, I've created a petition to get NPM's attention to prevent this from happening, please sign and share this petition to show NPM we demand better security procedures on released packages!
> 
> https://www.change.org/p/npm-please-secure-package-releasing

Yes, it needs to be enforced. I had to reboot my whole windows computer and change major apsswords because of this. It was a long week.

**Comment by PrivateGER** [comment]
Would you people please stop cluttering this already gigantic thread with garbage like a change.org petition? This is software development, stop creating petitions and raise an issue over at npm instead.

**Comment by sharedrory** [comment]
> Hello all, I've created a petition to get NPM's attention to prevent this from happening, please sign and share this petition to show NPM we demand better security procedures on released packages!
> 
> https://www.change.org/p/npm-please-secure-package-releasing

Sorry to post this here but
> Automatically scan packages for vulnerabilities before being released to the general public
This would only be able to catch whatever is already known.

Part of the real problem is that you can't even see the source code of npm packages without downloading them. If npm made normal users and not just teams have access to the files tab then that would be a great step towards a secure future.
Furthermore, display not the whole package.json, not the entire scripts sections, but even just the scripts that npm runs on the package lifecycle events such as install on the package page would help. This all belongs somewhere where npm will see it and not here but I just wanted to say that this is one of the only ways we can solve the problem.

**Comment by ljharb** [comment]
@sharedrory yes, you can. https://unpkg.com/ua-parser-js, and npm itself when logged in has an "explore" tab.

**Comment by mensfeld** [comment]
@sharedrory for code changes you can use mentioned before diffend platform: https://my.diffend.io/npm/ua-parser-js/0.7.28/0.7.29

**Comment by sharedrory** [comment]
> @sharedrory yes, you can. https://unpkg.com/ua-parser-js, and npm itself when logged in has an "explore" tab.

That is not npm. Why should you have to be logged in. Even then its useless as most packages are "too big" to be displayed.

> @sharedrory for code changes you can use mentioned before diffend platform: https://my.diffend.io/npm/ua-parser-js/0.7.28/0.7.29

That is not npm.

**Comment by krishnaUIDev** [comment]
@ccravens i think you can make petition to npm that they have to scan this kind of Malwares while publishing to the library. ￼￼￼

**Comment by gugu** [comment]
@krishnaUIDev do you solve every problem with a petition?

**Comment by krishnaUIDev** [comment]
> @krishnaUIDev do you solve every problem with a petition?

I this thats the one way.

**Comment by ljharb** [comment]
npm - like almost everything else - doesn’t make decisions by petition.

**Comment by KalleOlaviNiemitalo** [comment]
According to [GitHub's commitment to npm ecosystem security](https://github.blog/2021-11-15-githubs-commitment-to-npm-ecosystem-security/) in the GitHub blog, the NPM team is already working on automated malware detection. NPM will also start requiring two-factor authentication "for maintainers and admins of popular packages" next year.

**Comment by PrivateGER** [comment]
> 
> 
> > @krishnaUIDev do you solve every problem with a petition?
> 
> I think this the one way.

No, the _one way_ is the issue tracker over at [npm/rfcs](https://github.com/npm/rfcs/discussions). Literally no software project makes decision by petition.

**Comment by varunsh-coder** [comment]
Most of the times compromised packages make outbound calls that are not expected, either to exfiltrate credentials or download additional malicious software. 

I have implemented [step-security/harden-runner](https://github.com/step-security/harden-runner) which is a GitHub Action that first correlates outbound traffic and then lets you create a policy to block outbound traffic from GitHub Action workflows. This can help detect compromised packages and prevent exfiltration of credentials. You can try out the hands-on tutorial here: https://github.com/step-security/supply-chain-goat/blob/main/RestrictOutboundTraffic.md. 

This helped detect unnecessary outbound traffic from Github-hosted runner, which is being addressed by disabling unnecessary services in the Actions VM (see the issue [here](https://github.com/actions/virtual-environments/issues/4867)). 

Please try it out. You might find unexpected outbound traffic in your workflows (e.g. end to end testing workflows).

**Comment by phydroxide** [comment]
This discussion references DLLs which makes me wonder what is the impact at all for use on linux? I Also did not see reference to where the actual malicious code was in the bundle. Our scanner alerted us to this because of a Dockerfile that introduced the module:
```
  apt-get install -y --no-install-recommends \
    sudo \
    inotify-tools \
    apt-utils \
    nodejs \
```
But it appears it is a false positive, given the configuration allows   `"ua-parser-js": "^0.7.18"` but the package resolves to https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.21.tgz


```
# find / -name '*'.json -exec grep ua-parser-js {} \; -exec echo {} \;
  "name": "ua-parser-js",
/root/package/bower.json
  "name": "ua-parser-js",
  "homepage": "http://github.com/faisalman/ua-parser-js",
    "url": "https://github.com/faisalman/ua-parser-js.git"
  "bugs": "https://github.com/faisalman/ua-parser-js/issues",
  "demo": "https://faisalman.github.io/ua-parser-js",
  "download": "https://raw.github.com/faisalman/ua-parser-js/master/dist/ua-parser.min.js"
/root/package/package.json
        "ua-parser-js": "^0.7.18"
    "ua-parser-js": {
      "resolved": "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.21.tgz",
/usr/lib/node_modules/npm/docs/package-lock.json
```
I try grabbing 0.7.29.tgz for comparison but it appears to have been pulled. Is that true? 

I also downloaded and unzipped https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.21.tgz and am looking for the files referenced but do not see them. 

So my question is, at this point is there any risk remaining that anyone would be afflicted by this? What are those conditions? They'd have to have built based upon this during a particular time range yes? How would one go about historical indicators that they'd been compromised?

**Comment by DanielRuf** [comment]
@phydroxide the malicious versions were quickly removed after they were found. That was some months ago. In the comment above there and in the articles of bleeping computer, Sonatype and so on the payload was described. Only Linux and Windows users were targeted.

https://www.bleepingcomputer.com/news/security/popular-npm-library-hijacked-to-install-password-stealers-miners/amp/

https://blog.sonatype.com/npm-project-used-by-millions-hijacked-in-supply-chain-attack

The articles contain IoCs and details about the names of the cryptominer and files.

Currently there is no more threat. .21 is safe / clean.
