### ISSUE TITLE
Prevent ua-parser-js install during npm install

### ISSUE THREAD

**Issue by Tanveer178** [faisalman/ua-parser-js#552]
Hello,

I was wondering if its possible to prevent the install of ua-parser-js while executing the command - “npm install”.

I see that the parser is present as devDependency in package.json of stream-http module of the various node_modules that gets downloaded automatically during npm install. Hence, I was thinking if we have a way to control or prevent this dependency install.

Looking forward to getting assistance in this.

**Comment by faisalman** [comment]
This kind of technical question might be more appropriate to be asked in forums like stackoverflow.com rather than opening a github issue
