### ISSUE TITLE
getResult() retuning normal parsed UA on localhost but empty on Vercel nextjs deployment

### ISSUE THREAD

**Issue by joneath** [faisalman/ua-parser-js#556]
I'm using the following code in a react component to determine browser version which works wonderfully in dev on localhost but once I deploy the Next.js app to Vercel the entire results object (besides the UA string) is empty.

```
const uaParser = new UAParser();
const parsedUa = uaParser.getResult();
```

**Localhost `getResult()`**
```
{
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "browser": {
        "name": "Chrome",
        "version": "95.0.4638.69",
        "major": "95"
    },
    "engine": {
        "name": "Blink",
        "version": "95.0.4638.69"
    },
    "os": {
        "name": "Mac OS",
        "version": "10.15.7"
    },
    "device": {},
    "cpu": {}
}
```

**Deployed `getResult()`**
```
{
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "browser": {},
    "engine": {
        "name": "Blink"
    },
    "os": {
        "name": "Mac OS"
    },
    "device": {},
    "cpu": {}
}
```

If I copy the source for `us-parser-js` and paste it into the Chrome's console while running the deployed app I get a full results object from `getResults()`. Any thoughts on what might be happening here?

**Comment by faisalman** [comment]
That's odd, I haven't come across a case like this, might be some failure in the server configuration?
