### ISSUE TITLE
Typescript types for browser name

### ISSUE THREAD

**Issue by DerZyklop** [faisalman/ua-parser-js#560]
This project has an entry in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ua-parser-js). I suggested to them, that it would be nice to have more fine-grained types for the browser name. E.g. to have code completion when working with the browser name.

I wrote this type:
```typescript
export type CommonBrowserNames = 'Amaya' | 'Android Browser' | 'Arora' | 'Avant' | 'Baidu' | 'Blazer' | 'Bolt' | 'Camino' | 'Chimera' | 'Chrome' | 'Chromium' | 'Comodo Dragon' | 'Conkeror' | 'Dillo' | 'Dolphin' | 'Doris' | 'Edge' | 'Epiphany' | 'Fennec' | 'Firebird' | 'Firefox' | 'Flock' | 'GoBrowser' | 'iCab' | 'ICE Browser' | 'IceApe' | 'IceCat' | 'IceDragon' | 'Iceweasel' | 'IE' | 'IE Mobile' | 'Iron' | 'Jasmine' | 'K-Meleon' | 'Konqueror' | 'Kindle' | 'Links' | 'Lunascape' | 'Lynx' | 'Maemo' | 'Maxthon' | 'Midori' | 'Minimo' | 'MIUI Browser' | 'Safari' | 'Mobile Safari' | 'Mosaic' | 'Mozilla' | 'Netfront' | 'Netscape' | 'NetSurf' | 'Nokia' | 'OmniWeb' | 'Opera Mini' | 'Opera Mobi' | 'Opera Tablet' | 'Phoenix' | 'Polaris' | 'QQBrowser' | 'RockMelt' | 'Silk' | 'Skyfire' | 'SeaMonkey' | 'SlimBrowser' | 'Swiftfox' | 'Tizen' | 'UCBrowser' | 'Vivaldi' | 'w3m' | 'Yandex';
```

Problem is: Someone would have to maintain the list of possibly returned types. It seems like this repo here is the better place to maintain the list of possible returned browser names. So this is the reason why I started this tread. Just in case you are interested in typescript types, too.

Some discussion happened here:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57497

**Comment by linonetwo** [comment]
interesting, the package is `user-agent` , but type is `@types/ua-parser-js` ?

**Comment by linonetwo** [comment]
Oh, I mislead by the readme,  https://github.com/faisalman/ua-parser-js#constructor

```
let parser = new UAParser("user-agent"); // you need to pass the user-agent for nodejs
```

it is acturally `ua-parser-js`

**Comment by faisalman** [comment]
Any issue with types might be more relevant here: https://github.com/DefinitelyTyped/DefinitelyTyped
