### ISSUE TITLE
Incorrect browser

### ISSUE THREAD

**Issue by richex-cn** [faisalman/ua-parser-js#563]
These are some UAS I found in the nginx log, Their browser cannot be parsed correctly,

```
Mozilla/5.0 (Linux; U; Android 10; zh-CN; V2034A Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.33 Mobile Safari/537.36 UCBS/3.22.2.33_211025173018 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:WIFI,ws:360|0|2.0) AliApp(AP/10.2.51.7100) AlipayClient/10.2.51.7100 Language/zh-Hans useStatusBar/true isConcaveScreen/true Region/CNAriver/1.0.0
Mozilla/5.0 (Linux; U; Android 9; zh-CN; vivo X21A Build/PKQ1.180819.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.33 Mobile Safari/537.36 UCBS/3.22.2.33_211025173018 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:4G,ws:360|0|3.0,ac:sp) AliApp(AP/10.2.51.7100) AlipayClient/10.2.51.7100 Language/zh-Hans useStatusBar/true isConcaveScreen/true Region/CNAriver/1.0.0
Mozilla/5.0 (Linux; U; Android 10; zh-CN; LIO-AN00m Build/HUAWEILIO-AN00m) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.33 Mobile Safari/537.36 UCBS/3.22.2.33_211025173018 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:4G,ws:461|0|2.55) AliApp(AP/10.2.51.7100) AlipayClient/10.2.51.7100 Language/zh-Hans useStatusBar/true isConcaveScreen/true Region/CNAriver/1.0.0
```

The result looks like this:

```
{
  "ua": "Mozilla/5.0 (Linux; U; Android 10; zh-CN; V2034A Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.33 Mobile Safari/537.36 UCBS/3.22.2.33_211025173018 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:WIF",
  "browser": {
    "name": "Android Browser",
    "version": "4.0",
    "major": "4"
  },
  "engine": {
    "name": "Blink",
    "version": "69.0.3497.100"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "vendor": "Vivo",
    "model": "V2034A",
    "type": "mobile"
  },
  "cpu": {},
  "gpu": {
    "vendor": "AMD",
    "model": "AMD Radeon Graphics"
  }
}
```

Can make url-parser-js correctly identify this?

**Comment by EnriqueWood** [comment]
@richex-cn What would be your expected output here?

**Comment by faisalman** [comment]
Can you provide more context to this issue? please use this format for clarity:

--

**Describe the bug**
...

**To Reproduce**
Steps to reproduce the behavior:
...

**Expected behavior**
...

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by faisalman** [comment]
I'm closing this for now, please reopen if you still facing the issue

**Comment by richex-cn** [comment]
Sorry for the late reply. @faisalman @EnriqueWood 

**Describe the bug**
`AlipayClient/*` means open in Alipay APP, 

**To Reproduce**
[Mozilla/5.0 (Linux; U; Android 10; zh-CN; V2034A Build/QP1A.190711.020) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.33 Mobile Safari/537.36 UCBS/3.22.2.33_211025173018 NebulaSDK/1.8.100112 Nebula AlipayDefined(nt:WIFI,ws:360|0|2.0) AliApp(AP/10.2.51.7100) AlipayClient/10.2.51.7100 Language/zh-Hans useStatusBar/true isConcaveScreen/true Region/CNAriver/1.0.0](https://uaparser.js.org/?ua=Mozilla/5.0%20(Linux;%20U;%20Android%2010;%20zh-CN;%20V2034A%20Build/QP1A.190711.020)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/69.0.3497.100%20UWS/3.22.2.33%20Mobile%20Safari/537.36%20UCBS/3.22.2.33_211025173018%20NebulaSDK/1.8.100112%20Nebula%20AlipayDefined(nt:WIFI,ws:360|0|2.0)%20AliApp(AP/10.2.51.7100)%20AlipayClient/10.2.51.7100%20Language/zh-Hans%20useStatusBar/true%20isConcaveScreen/true%20Region/CNAriver/1.0.0#try)

**Expected behavior:**

```
  "browser": {
    "name": "Alipay",
    "version": "10.2.51.7100",
    "major": "10"
  }
```

**Actually happening:**

```
  "browser": {
    "name": "Android Browser",
    "version": "4.0",
    "major": "4"
  }
```

**Additional comments:**

Just like WeChat APP, I think it's normal: [Mozilla/5.0 (iPhone; CPU iPhone OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Mobile/10B329 MicroMessenger/5.0.1](https://uaparser.js.org/?ua=Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%206_1_3%20like%20Mac%20OS%20X)%20AppleWebKit/536.26%20(KHTML,%20like%20Gecko)%20Mobile/10B329%20MicroMessenger/5.0.1#try)

```
  "browser": {
    "name": "WeChat",
    "version": "5.0.1",
    "major": "5"
  }
```
