### ISSUE TITLE
Wrong MacOS version

### ISSUE THREAD

**Issue by equinusocio** [faisalman/ua-parser-js#564]
It seems everything is wrong. I'm using Chrome on MacOS 12.1..
![Screenshot 2022-01-14 at 11 13 32](https://user-images.githubusercontent.com/10454741/149498740-34202d42-4214-4478-aa75-4e93afe54a82.png)

**Comment by fuadop** [comment]
I don't think `User-Agnet` header is always perfect. It can't always be @equinusocio

**Comment by MitchTalmadge** [comment]
There's unfortunately nothing that can be done to fix this by UA-Parser. Your browser reports the wrong version. That's pretty much how life is these days sadly.
