### ISSUE TITLE
Testing on Chrome, Firefox, and Edge version 100?

### ISSUE THREAD

**Issue by jparismorgan** [faisalman/ua-parser-js#567]
This article points out concerns about Chrome, Firefox, and Edge hitting version 100 and the impact of that on user agent parsing libraries: https://www.theverge.com/2022/2/17/22938721/chrome-firefox-edge-version-100-websites-bug-compatibility-issues-mozilla-google-microsoft

Has there been testing of ua-parser-js on whether anything will be broken?

**Comment by jparismorgan** [comment]
Ended up testing and things look okay: https://github.com/faisalman/ua-parser-js/pull/568

**Comment by faisalman** [comment]
The bug can be happened when comparing version number using string, like what was once found in slack [1]

```
if (browser.version > '52')
```

up until `'99'` the result would still be `TRUE` but once the browser is turning `'100'` it would be `FALSE`, which is not the intended result.

[1] https://github.com/webcompat/web-bugs/issues/67866

**Comment by jparismorgan** [comment]
Thanks @faisalman, so you can also confirm you believe things will work for version 100? If so please go ahead and close this issue!

Also, calling out a comment on the tests I added: 
```
My understanding is this will work until Chrome 107 - https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html - after that user agent string will be with reduced information and from that point forward folks should rely on navigator.userAgentData ie. the User Agent Client Hints - https://web.dev/user-agent-client-hints/

Feature request for Client Hints -> https://github.com/faisalman/ua-parser-js/issues/408
```

This could be addressed in a separate issue, but seems concerning.
