### ISSUE TITLE
Huawei browser detected as chrome

### ISSUE THREAD

**Issue by guoguokakukaku** [faisalman/ua-parser-js#569]
Hello
Huawei browser detected as chrome
ua sample: "Mozilla/5.0 (Linux; Android 10; POT-LX2J; HMSCore 3.0.3.303; GMSCore 21.42.18) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 HuaweiBrowser/11.0.8.303 Mobile Safari/537.36"

**Comment by jparismorgan** [comment]
Hi @guoguokakukaku, I have a PR for this same issue here: https://github.com/faisalman/ua-parser-js/pull/570
