### ISSUE TITLE
ios device details null

### ISSUE THREAD

**Issue by nilay9** [faisalman/ua-parser-js#584]
`With IOS device, from user agent model details are not fetched. these is my user-agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15`

**Comment by faisalman** [comment]
Fixed in https://github.com/faisalman/ua-parser-js/commit/a88660493568d6144a551424a8139d6c876635f6
