### ISSUE TITLE
Please add support for Yandex App

### ISSUE THREAD

**Issue by Vlad-coder-678** [faisalman/ua-parser-js#587]
Here is the link to the app https://play.google.com/store/apps/details?id=ru.yandex.searchplugin

user-agent two years ago:
Mozilla/5.0 (Linux; Android 7.0; ASUS_X00KD Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36 YaApp_Android/9.75 YaSearchBrowser/9.75

now:
Mozilla/5.0 (Linux; arm_64; Android 11; M2101K7AG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.125 YaApp_Android/22.70 YaSearchBrowser/22.70 BroPP/1.0 SA/3 Mobile Safari/537.36

It's identified as "Chrome" browser. But should be "Yandex"

**Comment by faisalman** [comment]
Fixed https://github.com/faisalman/ua-parser-js/commit/33f02099d1bf2e074446c0608c4fbfcd22371475
