### ISSUE TITLE
new release / tag

### ISSUE THREAD

**Issue by slawn** [faisalman/ua-parser-js#592]
Will there be a new release any time soon? Last one was Oct 2021 - and there were good few commits since then and some of them important like increasing UA_MAX_LENGTH to 350? Thanks

**Comment by Mon0Man** [comment]
I am also wondering too. seem like faisalman is not really active.

**Comment by faisalman** [comment]
Done

**Comment by jmaicher** [comment]
Hey @faisalman, `1.0.2` to `1.0.32` is an unconventional version bump. Can you confirm that it's a legit release?

**Comment by faisalman** [comment]
Since `1.x` is basicly just a mirror of `0.7.x`, I think the patch-level version should be the same, just for convenience..
