### ISSUE TITLE
Browser version not detected on iPadOS 15.7

### ISSUE THREAD

**Issue by kochalex** [faisalman/ua-parser-js#594]
iPadOS 15.7 is returning a user agent string with a comma in the version, `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Safari/605.1.15` and `ua-parser-js` is not finding browser version information from it.

I do not have access to an iOS 15.7 version device to see if the user agent is the same.

for `getBrowser()`, this is returned:
```js
{name: "Safari", version: undefined, major: undefined}
```

**Comment by faisalman** [comment]
Fixed in #595

**Comment by michalsnik** [comment]
When can we expect a patch release @faisalman ?

**Comment by nickvergessen** [comment]
@faisalman can you release a 1.0.3?
