### ISSUE TITLE
Surface Pro 7 in Chrome simulator as iPad

### ISSUE THREAD

**Issue by hankeliu2015** [faisalman/ua-parser-js#614]
In Chrome dev tool mobile simulator, when choose Surface Pro 7, getDevice().model shows iPad. See screenshots. If need more details, please let me know. thanks!
![Screen Shot 2022-11-29 at 2 50 18 PM](https://user-images.githubusercontent.com/16155615/204641203-40ba7033-9d28-4e9a-a1b4-2c9f02629c65.png)
![Screen Shot 2022-11-29 at 2 50 25 PM](https://user-images.githubusercontent.com/16155615/204641206-46d8d317-0bef-40a0-85c0-58885892bad6.png)

**Comment by faisalman** [comment]
Fixed https://github.com/ChromeDevTools/devtools-frontend/commit/fad94a03d5c58df6e0d88d79f81198ebde4b52ca
