### ISSUE TITLE
Vulnerability sonatype-2018-0272

### ISSUE THREAD

**Issue by LucasLopesr** [faisalman/ua-parser-js#615]
I'm getting the indication of vulnerability in this package, has anyone checked it yet? is this safe?

https://ossindex.sonatype.org/vulnerability/sonatype-2018-0272?component-type=npm&component-name=ua-parser-js&utm_source=dependency-track&utm_medium=integration&utm_content=v4.4.2

**Comment by faisalman** [comment]
This has been fixed in https://github.com/faisalman/ua-parser-js/commit/50bd78afb140136deef245dcf95052bd8f0bc27e
