### ISSUE TITLE
Internet Explorer 11 / Windows 8.1

### ISSUE THREAD

**Issue by bathos** [faisalman/ua-parser-js#62]
This is what I get back:

```
{
    browser: {
        name: undefined,
        version: undefined,
        major: undefined
    },
    engine: {
        name: 'Trident',
        version: '7.0'
    },
    os: {
        name: 'Windows',
        version: 'NT 6.3'
    },
    device: {
        model: undefined,
        vendor: undefined,
        type: undefined
    },
    cpu: {
        architecture: undefined
    }
}
```

**Comment by mikemaccana** [comment]
Ditto. `window.navigator.userAgent` is:

> "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; rv:11.0) like Gecko"
![screen shot 2015-01-16 at 17 48 59](https://cloud.githubusercontent.com/assets/172594/5781149/2e61cd58-9da8-11e4-8567-443a08f8d29d.png)

**Comment by elmonty** [comment]
I am getting "Chrome 45" instead of IE 11 on Win 8.1. This problem still exists.

**Comment by faisalman** [comment]
Fixed already
