### ISSUE TITLE
Asus device undefined 

### ISSUE THREAD

**Issue by laclance** [faisalman/ua-parser-js#622]
Device model: VivoBook_ASUSLaptop X515FAC_X515FA

```    
const parser = new UAParser(navigator.userAgent);
console.log(parser.getResult())
```
    
prints:

```
browser: {name: 'Chrome', version: '108.0.0.0', major: '108'}
cpu: {architecture: 'amd64'}
device: {vendor: undefined, model: undefined, type: undefined}
engine: {name: 'Blink', version: '108.0.0.0'}
os: {name: 'Windows', version: '10'}
ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by Ahman9950** [comment]
> Device model: VivoBook_ASUSLaptop X515FAC_X515FA
> 
> ```    
> const parser = new UAParser(navigator.userAgent);
> console.log(parser.getResult())
> ```
>     
> prints:
> 
> ```
> browser: {name: 'Chrome', version: '108.0.0.0', major: '108'}
> cpu: {architecture: 'amd64'}
> device: {vendor: undefined, model: undefined, type: undefined}
> engine: {name: 'Blink', version: '108.0.0.0'}
> os: {name: 'Windows', version: '10'}
> ua: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
> ```
>

**Comment by faisalman** [comment]
I think this is the intended result since none about the device is actually provided within user-agent string
