### ISSUE TITLE
使用鸿蒙设备时显示的是它对应所兼容的安卓版本的版本号，而不是鸿蒙版本号。

### ISSUE THREAD

**Issue by heStudio-Network** [faisalman/ua-parser-js#623]
使用鸿蒙设备时显示的是它对应所兼容的安卓版本的版本号，而不是鸿蒙版本号。![209415647-662ae8a0-4597-4ddc-a3c8-9d73c875678a.jpg](https://user-images.githubusercontent.com/119711513/209600624-afe8c9c2-0e48-4c62-9e23-84c734ca8396.jpg)

问题对应链接：https://www.hestudio.org/talking/#54

**Comment by faisalman** [comment]
It's kind of a workaround since HarmonyOS doesn't include its version in their user-agent string
