### ISSUE TITLE
Amazon Echos + windows 11 are not defined

### ISSUE THREAD

**Issue by redimongo** [faisalman/ua-parser-js#624]
I know this script was nether meant to be able detect everything but I noticed a few issues.

Noticed that the windowsVersionMap does not support Windows 11. Is it even possible? Rumour has it that Windows 11 browsers are reporting as Windows 10.
```
 windowsVersionMap = {
            'ME'        : '4.90',
            'NT 3.11'   : 'NT3.51',
            'NT 4.0'    : 'NT4.0',
            '2000'      : 'NT 5.0',
            'XP'        : ['NT 5.1', 'NT 5.2'],
            'Vista'     : 'NT 6.0',
            '7'         : 'NT 6.1',
            '8'         : 'NT 6.2',
            '8.1'       : 'NT 6.3',
            '10'        : ['NT 6.4', 'NT 10.0'],
            'RT'        : 'ARM'
```

Also our users are accessing our system using `Echo/1.0(APNG)` now we know that that is Amazon, Echo devices. sadly we are not able to tell what device it. How do we add this to the software.

**Comment by BriannaMason6770927** [comment]
The automatic update to Windows 11, version 22H2 will happen gradually starting with those devices that have been using version 21H2 for the longest period of time.
