### ISSUE TITLE
Not showing my CPU or device type? 

### ISSUE THREAD

**Issue by ovived** [faisalman/ua-parser-js#626]
My UA = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

Not getting TYPE , MODEL or CPU

(blank)

Any ideas? 

```
 (log) {
  ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36',
  browser: { name: 'Chrome', version: '108.0.0.0', major: '108' },
  engine: { name: 'Blink', version: '108.0.0.0' },
  os: { name: 'Mac OS', version: '10.15.7' },
  device: {},
  cpu: {}
}
```

**Comment by faisalman** [comment]
As of `0.7.33`, this can be identified as Apple Macintosh https://github.com/faisalman/ua-parser-js/commit/a88660493568d6144a551424a8139d6c876635f6

```
device : {
  vendor : 'Apple',
  model : 'Macintosh'
  type: undefined
}
```
