### ISSUE TITLE
Please add support for Yandex App

### ISSUE THREAD

**Issue by sergeivaskin1991** [faisalman/ua-parser-js#628]
Here is the link to the app https://play.google.com/store/apps/details?id=ru.yandex.searchplugin and app - https://play.google.com/store/apps/details?id=com.yandex.searchapp&hl=ru&gl=US

user-agent: YaApp_Android/version and YaSearchApp/version

It's identified as "Chrome" browser. But should be "Yandex app"

**Comment by BriannaMason6770927** [comment]
this app is amazing! and something i have enjoyed using.

**Comment by faisalman** [comment]
Duplicate of #587
