### ISSUE TITLE
Please fix latest tag on npmjs.com

### ISSUE THREAD

**Issue by zdm** [faisalman/ua-parser-js#630]
Current latest version is `1.0.33`.
But on `npmjs.com` version `0.7.33` is marked as latest.
This is mistake and was happened several days ago, when you released latest version.

```
$>npm ou
Package       Current  Wanted  Latest  Location                   Depended by
ua-parser-js   1.0.33     1.0.33    0.7.33  node_modules/ua-parser-js  core

```

**Comment by faisalman** [comment]
I just found out that npm is assigning `latest` version to the most recent published version rather than by semver convention. Fixed this using `npm dist-tag`.

cc #629
