### ISSUE TITLE
1.0.x vs 0.7.x is still confusing :)

### ISSUE THREAD

**Issue by lydell** [faisalman/ua-parser-js#633]
This issue asked about 1.0.x vs 0.7.x:

https://github.com/faisalman/ua-parser-js/issues/629

And got the answer:

> 1.0.x is basically the same version as 0.7.x

This issue asked about breaking changes:

https://github.com/faisalman/ua-parser-js/issues/612

There don’t seem to be any differences except the version number.

This commit tried to clarify things:

https://github.com/faisalman/ua-parser-js/commit/cf093222e5a2dbdff1855539144e457c9c47a9d1

The now changelog says:

> Version 1.0.x is basically the equivalent of version 0.7.x. See https://github.com/faisalman/ua-parser-js/issues/536 for the reason behind this confusion.

There are two issues with that sentence:

- It says “basically” which makes it sound like the are differences, but it doesn’t say what.
- It links to a super long issue. Is there no short summary?

![image](https://user-images.githubusercontent.com/2142817/218779344-a0dff474-6d8f-4095-9ea7-122ce92a422d.png)

Suggestion: Is it time to jump to 1.0 “for real”? I know it wasn’t your decision to publish 1.0.x, but in my opinion this library is worthy of being 1.0 at this point :)

**Comment by faisalman** [comment]
I second that, a new non-confusing version will be on it's way now under `1.1` :+1:
