### ISSUE TITLE
Ipad consider as an Mac OS

### ISSUE THREAD

**Issue by ArunKathir98** [faisalman/ua-parser-js#638]
I want to hide option for iPad and iPhone.

I implemented the logic with 
if ( uaParser.getOS().name === "Mac OS" && uaParser.getDevice().type !== "mobile" && uaParser.getDevice().type !== "tablet" ) { 
// Set TRUE
}

it return true;

Did i missed some thing from the logic.

**Comment by faisalman** [comment]
Can you provide the user-agent that aren't detected as mobile/tablet? from `uaParser.getResult()`

**Comment by saltire** [comment]
```
{
  browser: {name: "Safari", version: "16.3", major: "16"},
  cpu: {architecture: undefined},
  device: {vendor: "Apple", model: "iPad", type: "tablet"},
  engine: {name: "WebKit", version: "605.1.15"},
  os: {name: "Mac OS", version: "10.15.7"},
  ua: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15",
}

```

**Comment by faisalman** [comment]
Thanks, should be ok then :+1:
