### ISSUE TITLE
Issues with `withClientHints()` in `2.0.0-alpha.1`

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [faisalman/ua-parser-js#640]
Hi, thank you for your work on the new version! Trying out the new function `.withClientHints()` I found some issues:

1. On Firefox (which does not support the user-agent client hints API), `.withClientHints()` does not return a Promise, and trying to `await` it causes an infinite loop. I guess it should return `Promise.resolve(unhinted)` instead.
2. It appears that only Chrome actually uses the user-agent client hints API: On Edge, the version string returned does not match the "about Edge" page.
3. It seems that this API always sets the browser name to Chromium, instead of leaving it as Chrome or Edge (I admit that I did not test Opera or Brave or other Chromium-based browsers).

**Comment by faisalman** [comment]
Thanks for the report, it's very helpful, I'll try to look into them.. :+1:
