### ISSUE TITLE
Device Type is undefined on Mac Desktop

### ISSUE THREAD

**Issue by tgowing** [faisalman/ua-parser-js#653]
**Describe the bug**
I am using a Mac computer and the device type is undefined.   This is the object that ua-parser is producing.

```
{
    "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
    "browser": {
        "name": "Chrome",
        "version": "113.0.0.0",
        "major": "113"
    },
    "engine": {
        "name": "Blink",
        "version": "113.0.0.0"
    },
    "os": {
        "name": "Mac OS",
        "version": "10.15.7"
    },
    "device": {
        "vendor": "Apple",
        "model": "Macintosh",
        **"type":  "undefined"**
    },
    "cpu": {}
}
```

**To Reproduce**

```
var uap = new UAParser();
console.log(uap.getResult());
```

**Comment by enkot** [comment]
I can confirm that the `device` type is `undefined` for this Mac user agent:
```js
import UAParser from "ua-parser-js"

const parser = new UAParser('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36')

console.log(parser.getDevice())
```
Result:
```sh
{ vendor: 'Apple', model: 'Macintosh', type: undefined }
```

**Comment by marmotz** [comment]
Not same OS, but there is a similar problem with my UA:

```js
import UAParser from "ua-parser-js"

const parser = new UAParser('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36')

console.log(parser.getDevice())
```
Result:
```js
{ vendor: undefined, model: undefined, type: undefined }
```

**Comment by majid4466** [comment]
Same here. 

With UAParser.js v2.0.0-alpha.3, this UA: `"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0"`
gives undefined for type, model and vendor:

`Object { type: undefined, model: undefined, vendor: undefined }`

**Comment by kblestarge** [comment]
This is happening for me on both version `1.0.37` and `2.0.0-beta.2`. Can someone fix this?

**Comment by muametgrooby** [comment]
This is not a bug, there's no such thing as desktop type, read more about it here: https://github.com/faisalman/ua-parser-js/issues/182

**Comment by faisalman** [comment]
> This is not a bug, there's no such thing as desktop type, read more about it here: #182

`undefined` device type for desktop is an intended behavior[^1]

[^1]: https://docs.uaparser.js.org/v2/api/ua-parser-js/get-device.html#type-string
