### ISSUE TITLE
Provide in-package type definitions

### ISSUE THREAD

**Issue by lnhrdt** [faisalman/ua-parser-js#655]
@faisalman I noticed there's a few issues/PRs where this has been discussed before:

https://github.com/faisalman/ua-parser-js/issues/560
https://github.com/faisalman/ua-parser-js/pull/432
https://github.com/faisalman/ua-parser-js/issues/423
https://github.com/faisalman/ua-parser-js/pull/326
https://github.com/faisalman/ua-parser-js/pull/320

but would you consider supporting the types for your project directly in this repository?

[@types/ua-parser-js](https://www.npmjs.com/package/@types/ua-parser-js) hasn't been updated in over 2 years and the types are out of date with [your upcoming 2.x release](https://github.com/faisalman/ua-parser-js/releases/tag/2.0.0-alpha.2). Maybe you know what I'm talking about, I noticed [even you have some `// @ts-ignore` suppressions in your tests](https://github.com/faisalman/ua-parser-js/blob/072a82b87ba35cc15ae10fd02d905f4b78a8ce05/test/playwright-test-browser.spec.mjs#L52-L53). It might be easier to support the types in-package.

**Comment by SUETAK** [comment]
> [@types/ua-parser-js](https://www.npmjs.com/package/@types/ua-parser-js) hasn't been updated in over 2 years and the types are out of date with [your upcoming 2.x release](https://github.com/faisalman/ua-parser-js/releases/tag/2.0.0-alpha.2). Maybe you know what I'm talking about, I noticed [even you have some // @ts-ignore suppressions in your tests](https://github.com/faisalman/ua-parser-js/blob/072a82b87ba35cc15ae10fd02d905f4b78a8ce05/test/playwright-test-browser.spec.mjs#L52-L53). It might be easier to support the types in-package.

I agree with this opinion.
google is moving forward with their intention to UH and a full transition is in sight.
I think the docs are misleading users because they recommend installing type/ua-parser-js but it is not really available.

**Comment by faisalman** [comment]
Maybe in the upcoming version I will also include the types.

I have modified the existing types in DefinitelyTyped, although not getting merged since v2.0 isn't released yet: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66330
