### ISSUE TITLE
Wrong OS version

### ISSUE THREAD

**Issue by Enfs-dev** [faisalman/ua-parser-js#658]
**Though I'm operating on Windows 11, It is showing Windows version as 10**

**Expected behavior**
Should provide exact OS version.

**Screenshots**
Windows Version :
![image](https://github.com/faisalman/ua-parser-js/assets/127836379/05ccc34b-7487-4f0e-97e3-184b77c8ce18)

getOS():
![image](https://github.com/faisalman/ua-parser-js/assets/127836379/0af1bc31-1d03-4bbe-86df-f015f2a44a4f)

**Desktop:**
 - OS: [Windows]
 - Browser [chrome]
 - Version [11]

**getUA()**
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'

**Comment by samueleastdev** [comment]
This issue seems to be a duplicate of this one - https://github.com/faisalman/ua-parser-js/issues/665

**Comment by faisalman** [comment]
Moved to #665
