### ISSUE TITLE
Get phone vendor using model

### ISSUE THREAD

**Issue by iojOMlyzI06b8nWnWfxI1BW** [faisalman/ua-parser-js#660]
I need a function to get the phone vendor from model name
Somethings like this: var vendor = GetVendor("SM-A605G");
I know that ua-parser-js contain that function but I dont know how to use it
It should be great if you export that function
Thank you!

**Comment by faisalman** [comment]
Currently we have no dedicated function that can identify vendor from its model, but I will consider it.
