### ISSUE TITLE
could not parse specific useragent while other vendor do

### ISSUE THREAD

**Issue by roy-algaly** [faisalman/ua-parser-js#664]
its not a bug, more of a missing ability to parse a useragents

user agent 
"iOS/14.8.1;iPad Mini 4;panda;19445;4.56.1"
expected :
os
string: iOS 14.8.1
family: iOS
major: 14
minor: 8
patch: 1

user agent
"com.google.Maps/6.73.0 iPad/16.5.1 hw/iPad6_11 (gzip)"

expected:
string: iOS 16.5.1
family: iOS
major: 16
minor: 5
patch: 1

used version 1.0.35

**Comment by faisalman** [comment]
I'm closing this for now, please reopen if you still facing the issue
