### ISSUE TITLE
Npm package of version 2 is not pubblished?

### ISSUE THREAD

**Issue by eatsjobs** [faisalman/ua-parser-js#666]
**Describe the bug**
v2 is is not published on npm

**To Reproduce**
```npm i ua-parser-js@2```

**Expected behavior**
install v2

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by faisalman** [comment]
Since version 2.0 is currently still under development, you can use `next` tag to install the latest unstable version of `ua-parser-js`:

`npm i ua-parser-js@next`
