### ISSUE TITLE
Do not use v2 alpha script in the demo page.

### ISSUE THREAD

**Issue by hyunbinseo** [faisalman/ua-parser-js#673]
Currently, the [demo] website uses `ua-parser-js@2.0.0-alpha.2` and this causes confusion.

[demo]: https://uaparser.js.org/

Notable examples are

1. macOS version detection — https://github.com/faisalman/ua-parser-js/issues/659#issuecomment-1689320154
2. Naver app browser detection — identified as `Whale@1.0.0.0` which is incorrect.

I am really excited about v2, but hope it is not used until it is stable.

**Comment by faisalman** [comment]
Hi @hyunbinseo, about the Naver app, can you provide us more info on why it's incorrect? along with its user-agent and what do you think the expected result should be. 


For a general bug report, you can use this following format:

--

**Describe the bug**
...

**To Reproduce**
Steps to reproduce the behavior:
...

**Expected behavior**
...

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by hyunbinseo** [comment]
Regarding the Naver app, seems like User-Agent Client Hints was the culprit.

```
+ ua-parser-js 1.0.36

{ name: 'KAKAOTALK', version: '2610370', major: '2610370' }
{ name: 'KAKAOTALK', version: '2409760', major: '2409760' }
{ name: 'NAVER', version: '11.25.12', major: '11' }
{ name: 'NAVER', version: '11.11.2', major: '11' }

+ ua-parser-js 2.0.0-alpha.3

IData { name: 'KAKAOTALK', version: '2610370', major: '2610370' }
IData { name: 'KAKAOTALK', version: '2409760', major: '2409760' }
IData { name: 'NAVER', version: '11.25.12', major: '11' }
IData { name: 'NAVER', version: '11.11.2', major: '11' }
```

Both v1 and v2 shows identical results in the CLI.

---

Maybe the [demo page](https://uaparser.js.org/#try)'s expression can be clarified?

I thought the user-agent string was the only data being used.

> For a given user-agent: ~
> {UAParser.js} will transforms it into a well-structured format: ~

According to the result however, seems like other data are used as well.

![Screenshot_20231001_160816_NAVER](https://github.com/faisalman/ua-parser-js/assets/47051820/67d4e6d8-566d-4c50-81c7-ff194f0a791a)

Naver app is determined as Whale 1.0.0.0 as shown above.

**Comment by faisalman** [comment]
> I thought the user-agent string was the only data being used.

It used to be, before the recent development of version 2.0

> Maybe the [demo page](https://uaparser.js.org/#try)'s expression can be clarified?

Second this, needs to be rephrased to also mentions the use of client hints data.

**Comment by faisalman** [comment]
The mentioned description in the demo page now has been rephrased
