### ISSUE TITLE
`withClientHints` not available in TS types

### ISSUE THREAD

**Issue by maphe** [faisalman/ua-parser-js#676]
**Library version**
v2.0.0-alpha.3

**Describe the bug**
`withClientHints` is not exposed in the `@types/ua-parser-js` package, making it unaccessible as TS will not compile.

**Comment by faisalman** [comment]
I have added a built-in TypeScript declarations just recently, please try using the latest published pre-release `v2.0.0-beta.1`

**Comment by maphe** [comment]
Cool, looking better with beta1 indeed. Thanks
