### ISSUE TITLE
Add support for Asus Padfone.

### ISSUE THREAD

**Issue by omega-tester** [faisalman/ua-parser-js#68]
Hello!
Please add support (device type identification) for https://www.asus.com/Tablets_Mobile/PadFone_2_A68/ which is capable to function as a mobile phone or a tablet (when inserted into dock station).

In mobile mode in Chrome UA string looks like
Mozilla/5.0 (Linux; Android 4.1.1; PadFone 2 Build/JRO03L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.117 Mobile Safari/537.36

In tablet mode in Chrome UA string looks like
Mozilla/5.0 (Linux; Android 4.1.1; PadFone 2 Build/JRO03L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.117 Safari/537.36

In mobile mode in Firefox UA string looks like
Mozilla/5.0 (Android; Mobile; rv:32.0) Gecko/32.0 Firefox/32.0.

In tablet mode in Firefox UA string looks like
Mozilla/5.0 (Android; Tablet; rv:32.0) Gecko/32.0 Firefox/32.0.

With best wishes,
A.

**Comment by faisalman** [comment]
Fixed
