### ISSUE TITLE
Samsung Internet reports a `browser.name` of `Samsung Browser` rather than `Samsung Internet`

### ISSUE THREAD

**Issue by aradalvand** [faisalman/ua-parser-js#694]
This is what v2.0.0-beta.1 returns when tested in Samsung Internet (notice that the `browser.name` is `Samsung Browser`, this used to be `Samsung Internet` in v1):
```json
{
    "ua": "Mozilla/5.0 (Linux; Android 10; Redmi 8A) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Mobile Safari/537.36",
    "browser": {
        "name": "Samsung Browser",
        "version": "23.0",
        "major": "23"
    },
    "cpu": {},
    "device": {
        "type": "mobile",
        "model": "Redmi 8A",
        "vendor": "Xiaomi"
    },
    "engine": {
        "name": "Blink",
        "version": "115.0.0.0"
    },
    "os": {
        "name": "Android",
        "version": "10"
    }
}
```

If this is intended, then it should be mentioned in v2's [list of breaking changes](https://github.com/faisalman/ua-parser-js/blob/master/CHANGELOG.md#version-20). Although it doesn't seem to be, because the browser enum still mentions `Samsung Internet`, which is strange:
https://github.com/faisalman/ua-parser-js/blob/3622b614a71749e6d96f241d6810d6086075e2a4/src/enums/ua-parser-enums.js#L118

**Comment by faisalman** [comment]
This has been fixed here: https://github.com/faisalman/ua-parser-js/commit/5c10e2b1070abb48f4549827533877f88139df93
