### ISSUE TITLE
Win11 Correct Detection (Client Hints)

### ISSUE THREAD

**Issue by dawesi** [faisalman/ua-parser-js#698]
**Library version**

**Describe the bug**
Windows 11 is detected incorrectly as brower UA shows win10

**To Reproduce**

Use Firefox/Edge on Win11

**Expected behavior**
OS Major Version 11

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox or Edge

**Additional context**

More context here: https://developers.whatismybrowser.com/learn/browser-detection/user-agents/detect-windows-11-user-agent

---

Microsoft provide detection script for detecting windows version 11 and greater here:

https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11#sample-code-for-detecting-windows-11

ie:
```
navigator.userAgentData.getHighEntropyValues(["platformVersion"])
 .then(ua => {
   if (navigator.userAgentData.platform === "Windows") {
     const majorPlatformVersion = parseInt(ua.platformVersion.split('.')[0]);
     if (majorPlatformVersion >= 13) {
       console.log("Windows 11 or later");
      }
      else if (majorPlatformVersion > 0) {
        console.log("Windows 10");
      }
      else {
        console.log("Before Windows 10");
      }
   }
   else {
     console.log("Not running on Windows");
   }
 });

```

**Comment by newinfinity12** [comment]
it is detected correctly for me. possibly not defining the client hints correctly
![win11](https://github.com/faisalman/ua-parser-js/assets/52183370/d607f4a7-2779-4c46-81a0-a845b49767fd)

**Comment by faisalman** [comment]
Can you provide a screenshot of whats being displayed in https://uaparser.js.org/ ?
