### ISSUE TITLE
HONOR needs to be separated from HUAWEI

### ISSUE THREAD

**Issue by pinganlong** [faisalman/ua-parser-js#704]
**Describe the bug**

there is a bug in the open-source project you provided on github (https://github.com/faisalman/ua-parser-js/blob/master/src/main/ua-parser.js#L504), the code is as follows. 

   // Huawei
            /\b((?:ag[rs][23]?|bah2?|sht?|btv)-a?[lw]\d{2})\b(?!.+d\/s)/i
            ], [MODEL, [VENDOR, HUAWEI], [TYPE, TABLET]], [
            /(?:huawei|honor)([-\w ]+)[;\)]/i,
            /\b(nexus 6p|\w{2,4}e?-[atu]?[ln][\dx][012359c][adn]?)\b(?!.+d\/s)/i
            ], [MODEL, [VENDOR, HUAWEI], [TYPE, MOBILE]], [

Honor has been re-established as an independent company who got no relation with Huawei.  Here are a few reports from 2021 for your ref. 
https://www.huawei.com/en/news/2020/11/huawei-honor-statement 
https://www.reuters.com/article/uk-huawei-technologies-m-a-digital-china-idUKKBN27W30E

**Expected behavior**
 Honor needs to be separated from Huawei. It is an independent brand, just like other brands // Huawei // Vivo // Realme

**Comment by Julias0** [comment]
I can take this up. Can you assign this to me?

**Comment by Julias0** [comment]
Let me know if any changes are required in the PR!

**Comment by pinganlong** [comment]
When can this problem be fixed? Thanks

**Comment by faisalman** [comment]
@Julias0 I've made a change request in the PR before I can merge.

@pinganlong Do you perhaps have any data regarding HONOR user agents that we can use for testing?

**Comment by Julias0** [comment]
I have added the fix in the PR and re-requested a review

**Comment by faisalman** [comment]
Merged

**Comment by pinganlong** [comment]
@faisalman @Julias0 1. 
I have  Honor devices. What steps can I follow to test and verify the modification?
2. Which version can include this modification?
Thank you.

**Comment by faisalman** [comment]
@pinganlong

1. You can add more test cases to this file: [`test/data/ua/device/honor.json`](https://github.com/faisalman/ua-parser-js/blob/master/test/data/ua/device/honor.json) then run `npm run test` to verify

```js
    {
        "desc": "...A short description of the device here...",
        "ua": "...Fill the UA string of the device here...",
        "expect": {
            "vendor": "Honor",
            "model": "...The expected device model here..",
            "type": "...mobile/tablet/or other device type here..."
        }
    }
```

2. The modification of separating HONOR from HUAWEI was already included in UAParser.js version `2.0.0`, you can try this in the demo page: https://uaparser.dev
