### ISSUE TITLE
Clearer guide for business-pro

### ISSUE THREAD

**Issue by NickSutton** [faisalman/ua-parser-js#706]
Hi,

Purchased business pro, received a license key that says 'inactive', with no mention where this needs to be entered? I have the script working for my needs just fine, but I was wondering what the point of the license key is?

**Comment by faisalman** [comment]
Hi, sorry for misunderstanding, I'll work on improving the getting-started guide for PRO licenses. Currently, the license key is only used as a proof of purchase (licensing compliance to use the packages under `@ua-parser-js` scope) and isn't being actively used in production code.
