### ISSUE TITLE
How to use 2.0? How to install?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [faisalman/ua-parser-js#714]
How to install 2.0 from NPM in a parcel project?
It doesn't seem to be uploaded.

**Comment by GviDoN94** [comment]
It's still a beta version, but if you want to use it: npm i ua-parser-js@2.0.0-beta.2

**Comment by GviDoN94** [comment]
> How to install 2.0 from NPM in a parcel project? It doesn't seem to be uploaded.

It's still a beta version, but if you want to use it: npm i ua-parser-js@2.0.0-beta.2

**Comment by royricht** [comment]
Can we have expected official release date for v2?

**Comment by GviDoN94** [comment]
> Can we have an expected official release date for v2 please?

Sorry, but I'm not the develper of this library, so I don't know.

**Comment by royricht** [comment]
thanks @GviDoN94 . @faisalman could you please assist with an estimation? :pray:

**Comment by faisalman** [comment]
No ETA yet, hopefully soon

**Comment by bharath-020** [comment]
hello , when will the version 2 cdn will release?
