### ISSUE TITLE
Export the enums

### ISSUE THREAD

**Issue by MarianoFacundoArch** [faisalman/ua-parser-js#715]
It would be nice if we could export the ENUMS to make comparisons later on without relying on strings, for example 
if (currentOsName === LINUX)

**Comment by faisalman** [comment]
You can use it already, just import the enums from [`'ua-parser-js/enums'`](https://github.com/faisalman/ua-parser-js/blob/master/src/enums/ua-parser-enums.js) submodule:

```js
import { UAParser } from 'ua-parser-js';
import { OS } from 'ua-parser-js/enums';

const ua = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.32';
const currentOSName = UAParser(ua).os.name;

if (currentOSName === OS.LINUX) {
    console.log('Hello! you are using Linux');
}
```

**Comment by hbbrawer-twitch** [comment]
Hi! Is this possible with the enterprise packages? I am doing the following:

```
import { type IBrowser, UAParser } from "@ua-parser-js/pro-enterprise";
import { OS } from "@ua-parser-js/pro-enterprise/enums";
...
```

I see the error: `Could not find a declaration file for module '@ua-parser-js/pro-enterprise/enums'.`

Looking in the @ua-parser-js node module, there is no `src/enums/ua-parser-enums.d.ts` file.

Any ideas what I am doing wrong here?
