### ISSUE TITLE
Easier way of combining all extensions

### ISSUE THREAD

**Issue by opablo** [faisalman/ua-parser-js#718]
While reading the 2.0.0-beta documentation here:
https://docs.uaparser.js.org/v2/api/submodules/extensions/overview.html

I learned that the required way of combining multiple Extensions is like this:

```
const botAndCLIParser = new UAParser(userAgentString, { browser : [...Bots.browser, ...CLIs.browser] })
```

it would be so much intuitive and simple to use if the library supports simply this:

```
const botAndCLIParser = new UAParser(userAgentString, [Bots, CLIs])
```

as an example of how ugly it can get... 
I wanted to implement the parsing of all possible known user agents and my code ended up like this:

```
  const uaParser = new UAParser(userAgent, {
    browser: [...Apps.browser, ...Bots.browser, ...CLIs.browser, ...Emails.browser, ...MediaPlayers.browser, ...Modules.browser],
    device: ExtraDevices.device
  })
  const uaParams = uaParser.getResult()
```

when it could have been as intuitive and simple as this:
```
  const uaParser = new UAParser(userAgent, [Apps, Bots, CLIs, Emails, ExtraDevices, MediaPlayers, Modules])
  const uaParams = uaParser.getResult()
```

**Comment by faisalman** [comment]
Thank you for this valuable suggestion, it's now possible to combine multiple extensions easily

```js
import { UAParser } from 'ua-parser-js';
import { Bots, Emails, InApps, MediaPlayers } from 'ua-parser-js/extensions';

const userAgent = 'curl/7.38.0';
const uaParser = new UAParser(userAgent, [Bots, Emails, InApps, MediaPlayers]);
const uaParams = uaParser.getResult();
```
