### ISSUE TITLE
Adding icons of each browser and os

### ISSUE THREAD

**Issue by loviuz** [faisalman/ua-parser-js#719]
**Is your feature request related to a problem? Please describe.**
I would print the browser name and os name with its own icons.

**Describe the solution you'd like**
I think that this library should contains all main icons for browsers and os.

**Describe alternatives you've considered**
The alternative is to implement this feature manually.

**Additional context**
This library could comes with default icons, and its name could be added in the resulting json:

```json
{
  "name": "Firefox",
  "version": "124.0",
  "major": "124",
  "icon": "firefox.png"
}
```

If this can be an interesting feature, I could be added by me with a pull request, but I do not want to spend time if this feature will not be added in the main repository.

Thanks in advance :-)

**Comment by shutter-codes** [comment]
Hey I want to work on this issue.
Can you please assign this to me.

**Comment by loviuz** [comment]
Wonderful! 🔥
