### ISSUE TITLE
Enquiries about UA parser PRO Enterprise

### ISSUE THREAD

**Issue by mustaphatg** [faisalman/ua-parser-js#726]
Hi there.

I am interested in purchasing the UA parser  PRO Enterprise.  I discovered there are limited information about it online.
First, I want to understand how it is offered. Once purchased, is the code shared and is any api call required to another service to verify or make use of it package.

Thanks

**Comment by faisalman** [comment]
If you have purchased it then you're eligible to download it manually or using npm. Currently there's no API call or another step required.

I'm closing this issue for now, if you have more question you can email me directly.
