### ISSUE TITLE
Implement userAgentData if applicable

### ISSUE THREAD

**Issue by AKaravas** [faisalman/ua-parser-js#729]
Modern browsers have implemented the navigator.userAgentData API. Is this supported? If not, are there plans to do so? On chrome and MacOS is active, and on firefox on an experimental version.

It is more accurate, and gives more information if a browser supports it.

**Comment by faisalman** [comment]
Hi thanks for using UAParser.js, the navigator.userAgentData API is already supported in our latest release (v2.0): https://github.com/faisalman/ua-parser-js/blob/2.0.0-beta.2/src/main/ua-parser.js#L95
