### ISSUE TITLE
Typo in pro-enterprise license document

### ISSUE THREAD

**Issue by theopak** [faisalman/ua-parser-js#735]
there's a minor grammatical error in the pro licenses. i think the line ought to say "We _retain_ all…" (singular, not plural) here:

https://github.com/faisalman/ua-parser-js/blob/10ec6349e24f46e536b83b23e8633281cc89f1ac/LICENSE.md?plain=1#L23

thank you for this library! i'd love to pay for it. but before i send a request to my employer's legal team to make that happen, i anticipate that they'd notice this typo and take it as a sign of untrustworthiness. was the license agreement written by a lawyer?

**Comment by faisalman** [comment]
Hi @theopak thanks for reporting the issue, I'll try to re-review the license text.

**Comment by faisalman** [comment]
Fixed in d50be39
