### ISSUE TITLE
NPM package version withClientHints incorrect

### ISSUE THREAD

**Issue by cgh20xx** [faisalman/ua-parser-js#739]
**Library version**
v2.0.0-alpha.3

UA String: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36

**Describe the bug**
I used npm i ua-parser-js@2.0.0-beta.3, but the information obtained with UAParser().withClientHints() is incorrect. The device.model shows as "K". However, when using the detection on the official website (https://uaparser.dev/), the result is correct, with device.model showing as "SM-S9060". I noticed that the JS version on the official website (https://uaparser.dev/js/ua-parser.js) is also 2.0.0-beta.3. Why is there a discrepancy in the results when using the same version?

**Smartphone (please complete the following information):**
 - Device: SAMSUNG Galaxy S22+ 5G SM-S9060
 - OS: android 14
 - Browser: chrome
 - Version: 123

**Comment by faisalman** [comment]
Hi @cgh20xx can you provide a working example that we can investigate? also check for the URL, since Client Hints are only sent when you browse from a secure context (https:// or localhost://).[^1]

[^1]: https://wicg.github.io/ua-client-hints/#secure-transport

**Comment by cgh20xx** [comment]
Thank you. It's working fine now that I'm using HTTPS.
