### ISSUE TITLE
Uncaught Error: Mismatched anonymous define() module

### ISSUE THREAD

**Issue by fizerkhan** [faisalman/ua-parser-js#74]
I have loaded `UAParser` after `require.js` library. I do not want to include `UAParser` in AMD module dependency.

```
<html>
  ...
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
   <script data-main="assets/js/main" src="assets/js/libs/require.js"></script>
   <script src="/scripts/ua-parser.min.js"></script>
   ...
</html>
```

It throws following error.

```
Uncaught Error: Mismatched anonymous define() module: function () {
                return UAParser;
            }

```

How do i fix it.

**Comment by faisalman** [comment]
Closed in #160

**Comment by schmkr** [comment]
Did this PR got undone? Current version on master is missing the name for the module again?

https://github.com/faisalman/ua-parser-js/blob/master/src/ua-parser.js#L885

**Comment by schmkr** [comment]
Ah, found it f28f87c.
