### ISSUE TITLE
Missing LICENSE file in the repo of ver 0.7.12

### ISSUE THREAD

**Issue by itsuki-murata** [faisalman/ua-parser-js#742]
Currently I'm using ua-parser-js version 0.7.12, but can't find a LICENSE file in the repo of ver 0.7.12.
Could you add the LICENSE file in the repo of ver 0.7.12?
Or is it possible to use the LICENSE file of the latest version as the license for ver 0.7.12?
Thanks in advance.

**Comment by faisalman** [comment]
Hi @itsuki-murata , you can find the license in package.json line 74:

https://github.com/faisalman/ua-parser-js/blob/01ae611dfa2d2c2ec3dba79c454538c0ed92e54f/package.json#L74

**Comment by itsuki-murata** [comment]
Thank you for reply.
Is it possible to use [the LICENSE file](https://github.com/faisalman/ua-parser-js/blob/0.7.x/license.md) as the license for ver 0.7.12?

**Comment by faisalman** [comment]
It's MIT then yes sure :+1:

**Comment by itsuki-murata** [comment]
Ok, I understand. Thank you for your reply.
