### ISSUE TITLE
Brave is faking UA to hide identity.

### ISSUE THREAD

**Issue by munir131** [faisalman/ua-parser-js#750]
**Library version**
Demo site

For the issue related with detection result, you can use the demo section in https://uaparser.dev to confirm

**Describe the bug**
Brave faking their user agent. https://brave.com/glossary/user-agent/#can-a-user-agent-string-reveal-my-identity

**To Reproduce**
1. Add `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36` on demo site. It should show that it is Brave

**Expected behavior**
It should show that it is Brave

**Comment by faisalman** [comment]
Hi @munir131, can you confirm what's being displayed on https://uaparser.dev/ when browsing from Brave? It should be detected as Brave since we also use feature detection.

**Comment by faisalman** [comment]
I'm closing this for now, please reopen if you still facing the issue

**Comment by munir131** [comment]
@faisalman As I mentioned in the description, it was tested on https://uaparser.dev/ It is not very concerning for me so not going to reopen. I wanted to let you know that this case drew your attention so this library can serve more accurately.
