### ISSUE TITLE
Android 14 wrongly detected as 10 on some phones

### ISSUE THREAD

**Issue by stnedelchev-fadv** [faisalman/ua-parser-js#760]
**Library version**
v2.0.0-beta.3 and v2.0.0-rc.1

For the issue related with detection result, you can use the demo section in https://uaparser.dev to confirm

**Describe the bug**
Android 14 wrongly detected as 10 on some devices (including my own).

**To Reproduce**
1. Download the latest build (currently 2.0.0 RC1) and use it in an HTML file (or alternatively just open the [UA Parser JS demo page](https://uaparser.dev/#demo).
2. Try to parse this User Agent `"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36"`

**Expected behavior**
Since I know I'm on an Android phone with Andriod 14, I would expect the library to detect the OS version as 14

**Screenshots**

![image](https://github.com/user-attachments/assets/7717d3b8-5937-429c-997d-10986c39d596)

![image](https://github.com/user-attachments/assets/9127a871-a776-4fe1-917d-e89d01b8b256)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10T Pro
 - OS: Android 14
 - Browser Chrome
 - Version 130

**Additional context**

Another weird thing is that I see correctly detected OS and device when I first open the demo page (without doing anything)

![image](https://github.com/user-attachments/assets/1ae56485-3a3d-4d05-bf00-b55ee66635e4)

But if I manually pass the same user agent to the manual input below, I get the result that I already described... as if the demo page uses something different initially. I also did a quick google search related to this issue and I found this article that might be related? https://mobiforge.com/research-analysis/the-mysterious-model-k

**Comment by stnedelchev-fadv** [comment]
Closing as I learned that I must be using the [withClientHints](https://docs.uaparser.dev/api/main/idata/with-client-hints.html) method to get advanced data from browsers that support `userAgentData` interface

**Comment by faisalman** [comment]
https://docs.uaparser.dev/guides/how-to-identify-android-k-device.html
