### ISSUE TITLE
Add Support for OpenHarmony UA Parsing in ua-parser-js

### ISSUE THREAD

**Issue by Anyexyz** [faisalman/ua-parser-js#769]
### Is your feature request related to a problem? Please describe.  
Currently, `ua-parser-js` does not recognize user agents (UAs) specific to OpenHarmony, making it challenging to correctly identify devices and browsers operating on this platform. For instance, a UA string like:  
```
Mozilla/5.0 (Phone; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile HuaweiBrowser/5.0.4.303
```  
is not properly parsed.  

### Describe the solution you'd like  
Add support for parsing OpenHarmony-specific UA strings in the `ua-parser-js` library. Specifically, this would involve recognizing:  
- Platform: `OpenHarmony`  
- Browser: `HuaweiBrowser`
- Device type: `Phone` (or other device types, if applicable)  
- Version information, such as `OpenHarmony 5.0`, `ArkWeb/4.1.6.1`, and `HuaweiBrowser/5.0.4.303`.  

### Describe alternatives you've considered  
A potential workaround is to pre-process UA strings externally before passing them to `ua-parser-js`. However, this adds unnecessary complexity and duplication of effort, as similar functionality is best suited to the `ua-parser-js` library.  

### Additional context  
OpenHarmony is an open-source operating system designed for IoT and mobile devices. Accurate UA parsing for OpenHarmony is increasingly important for compatibility and analytics purposes as the platform grows in popularity.  

If further information or test cases are needed, I’d be happy to provide examples and test data.

**Comment by faisalman** [comment]
Hi, thanks for reporting, support for `OpenHarmony` has been added since `v2.0.0-rc.1` in this commit: https://github.com/faisalman/ua-parser-js/commit/fe15f115f9c5b811e72836cb68a8497004976d64

Try running this:

```sh
npx ua-parser-js@2 "Mozilla/5.0 (Phone; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile HuaweiBrowser/5.0.4.303"
```

The result should be like the following:

```js
[
    {
        "ua": "Mozilla/5.0 (Phone; OpenHarmony 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 ArkWeb/4.1.6.1 Mobile HuaweiBrowser/5.0.4.303",
        "browser": {
            "name": "Huawei Browser",
            "version": "5.0.4.303",
            "major": "5"
        },
        "cpu": {},
        "device": {
            "type": "mobile"
        },
        "engine": {
            "name": "ArkWeb",
            "version": "4.1.6.1"
        },
        "os": {
            "name": "OpenHarmony",
            "version": "5.0"
        }
    }
]
```

Related issue: #754

**Comment by Anyexyz** [comment]
Nice, thank you for your help, I will close this issue.
