### ISSUE TITLE
Namespacing requirejs build

### ISSUE THREAD

**Issue by bstenm** [faisalman/ua-parser-js#92]
Just to let you know that your 'typeof(define)' line 745 of ua-parser.js needs to be written as 'typeof define' for the namespace option of the requirejs build to do its job (namely namespacing all 'define' instances).
Please refer to http://requirejs.org/docs/faq-optimization.html#namespace in the requirejs docs.
Thanks!

**Comment by austinpray** [comment]
ezpz: https://github.com/faisalman/ua-parser-js/pull/93

**Comment by bstenm** [comment]
actually it looks like it also needs the  'function' directly as a string rather than as a variable:
typeof define === 'function'  rather than typeof define === FUNC_TYPE
