### ISSUE TITLE
Opera Mobile for Android not identified as 'mobile' device

### ISSUE THREAD

**Issue by sheepsteak** [faisalman/ua-parser-js#97]
Device type is coming back `undefined` instead of `mobile` as expected.

User Agent:
`Mozilla/5.0 (Linux; Android 4.4.4; XT1032 Build/KXB21.14-L1.40) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Mobile Safari/537.36 OPR/27.0.1698.88647`

**Comment by faisalman** [comment]
Fixed in #145
