### ISSUE TITLE
Cyanogen / HTC

### ISSUE THREAD

**Issue by GabrielCousin** [faisalman/ua-parser-js#98]
Hello,
I am facing a problem detecting device type of the following device :
- HTC One M7 with CyanogenMod
- Cyanogen version : 12-20150215-NIGHTLY-m7
- Core : 3.4.105-g20f1de7

Can you help? Thanks in advance !

![Cyanogen](http://f.cl.ly/items/2Y1P1F1Y202p430r1g37/screenshot_2015-02-19-10-36-32_1024.png)

**Comment by faisalman** [comment]
No `HTC` phrase in user agent.. It's hard to know whether this agent is really HTC One M7 or not
